// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package prefer_optional_chain

import "github.com/go-json-experiment/json"

type PreferOptionalChainOptions struct {
	// Allow autofixers that will change the return type of the expression. This
	// option is considered unsafe as it may break the build.
	AllowPotentiallyUnsafeFixesThatModifyTheReturnTypeIKnowWhatImDoing bool `json:"allowPotentiallyUnsafeFixesThatModifyTheReturnTypeIKnowWhatImDoing,omitempty"`

	// Check operands that are typed as `any` when inspecting 'loose boolean'
	// operands.
	CheckAny bool `json:"checkAny,omitempty"`

	// Check operands that are typed as `bigint` when inspecting 'loose boolean'
	// operands.
	CheckBigInt bool `json:"checkBigInt,omitempty"`

	// Check operands that are typed as `boolean` when inspecting 'loose boolean'
	// operands.
	CheckBoolean bool `json:"checkBoolean,omitempty"`

	// Check operands that are typed as `number` when inspecting 'loose boolean'
	// operands.
	CheckNumber bool `json:"checkNumber,omitempty"`

	// Check operands that are typed as `string` when inspecting 'loose boolean'
	// operands.
	CheckString bool `json:"checkString,omitempty"`

	// Check operands that are typed as `unknown` when inspecting 'loose boolean'
	// operands.
	CheckUnknown bool `json:"checkUnknown,omitempty"`

	// Skip operands that are not typed with `null` and/or `undefined` when inspecting
	// 'loose boolean' operands.
	RequireNullish bool `json:"requireNullish,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PreferOptionalChainOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain PreferOptionalChainOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["allowPotentiallyUnsafeFixesThatModifyTheReturnTypeIKnowWhatImDoing"]; !ok || v == nil {
		plain.AllowPotentiallyUnsafeFixesThatModifyTheReturnTypeIKnowWhatImDoing = false
	}
	if v, ok := raw["checkAny"]; !ok || v == nil {
		plain.CheckAny = true
	}
	if v, ok := raw["checkBigInt"]; !ok || v == nil {
		plain.CheckBigInt = true
	}
	if v, ok := raw["checkBoolean"]; !ok || v == nil {
		plain.CheckBoolean = true
	}
	if v, ok := raw["checkNumber"]; !ok || v == nil {
		plain.CheckNumber = true
	}
	if v, ok := raw["checkString"]; !ok || v == nil {
		plain.CheckString = true
	}
	if v, ok := raw["checkUnknown"]; !ok || v == nil {
		plain.CheckUnknown = true
	}
	if v, ok := raw["requireNullish"]; !ok || v == nil {
		plain.RequireNullish = false
	}
	*j = PreferOptionalChainOptions(plain)
	return nil
}
