// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package prefer_promise_reject_errors

import "github.com/go-json-experiment/json"
import "github.com/SonarSource/SonarJS/server-go/sonar-server/internal/utils"

type PreferPromiseRejectErrorsOptions struct {
	// Type specifiers that can be used as Promise rejection reasons
	Allow []utils.TypeOrValueSpecifier `json:"allow,omitempty"`

	// AllowEmptyReject corresponds to the JSON schema field "allowEmptyReject".
	AllowEmptyReject bool `json:"allowEmptyReject,omitempty"`

	// AllowThrowingAny corresponds to the JSON schema field "allowThrowingAny".
	AllowThrowingAny bool `json:"allowThrowingAny,omitempty"`

	// AllowThrowingUnknown corresponds to the JSON schema field
	// "allowThrowingUnknown".
	AllowThrowingUnknown bool `json:"allowThrowingUnknown,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PreferPromiseRejectErrorsOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain PreferPromiseRejectErrorsOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["allow"]; !ok || v == nil {
		plain.Allow = []utils.TypeOrValueSpecifier{}
	}
	if v, ok := raw["allowEmptyReject"]; !ok || v == nil {
		plain.AllowEmptyReject = false
	}
	if v, ok := raw["allowThrowingAny"]; !ok || v == nil {
		plain.AllowThrowingAny = false
	}
	if v, ok := raw["allowThrowingUnknown"]; !ok || v == nil {
		plain.AllowThrowingUnknown = false
	}
	*j = PreferPromiseRejectErrorsOptions(plain)
	return nil
}
