container_definition: &CONTAINER_DEFINITION
  cluster_name: ${CIRRUS_CLUSTER_NAME}
  builder_role: cirrus-builder
  builder_image: docker-builder-v*
  builder_instance_type: t3.small
  region: eu-central-1
  namespace: default
  use_in_memory_disk: true
  cpu: 10
  memory: 40G

build_task:
  eks_container:
    <<: *CONTAINER_DEFINITION
    dockerfile: .cirrus/nodejs.Dockerfile
    docker_arguments:
      CIRRUS_AWS_ACCOUNT: ${CIRRUS_AWS_ACCOUNT}
      NODE_VERSION: 22
  arbitrary_cache:
    folder: arbitrary-cache
    populate_script:
      - mkdir arbitrary-cache
      - cp .cirrus/schemer-dreamer.webp arbitrary-cache
    fingerprint_script: echo "best album cover art ever"
  main_script:
    - wget google.com
    - ls -la arbitrary-cache

