env:
  CIRRUS_VAULT_URL: https://vault.sonar.build:8200
  CIRRUS_VAULT_AUTH_PATH: jwt-cirrusci
  CIRRUS_VAULT_ROLE: cirrusci-${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}

  ARTIFACTORY_URL: https://repox.jfrog.io/artifactory
  ARTIFACTORY_PRIVATE_USERNAME: vault-${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader
  ARTIFACTORY_PRIVATE_PASSWORD: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader access_token]
  ARTIFACTORY_DEPLOY_USERNAME: vault-${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-qa-deployer
  ARTIFACTORY_DEPLOY_PASSWORD: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-qa-deployer access_token]
  ARTIFACTORY_DEPLOY_REPO: sonarsource-public-qa
  ARTIFACTORY_ACCESS_TOKEN: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader access_token]
  GITHUB_TOKEN: VAULT[development/github/token/licenses-ro token]

  # Use bash (instead of sh on linux or cmd.exe on windows)
  CIRRUS_SHELL: bash

container_definition: &CONTAINER_DEFINITION
  cluster_name: ${CIRRUS_CLUSTER_NAME}
  builder_role: cirrus-builder
  builder_image: docker-builder-v*
  builder_instance_type: t3.small
  region: eu-central-1
  namespace: default
  use_in_memory_disk: true
  cpu: 10
  memory: 40G

maven_cache_definition: &MAVEN_CACHE
  maven_cache:
    folder: ${CIRRUS_WORKING_DIR}/.m2/repository
    fingerprint_script: |
      if [ "$CIRRUS_OS" = "windows" ]; then
        powershell.exe -NoLogo -Command "Get-ChildItem -Path . -Filter "pom.xml" -Recurse -ErrorAction SilentlyContinue -Force | cat"
      fi
      if [ "$CIRRUS_OS" = "linux" ]; then
        find . -name pom.xml -exec cat {} \+
      fi

orchestrator_cache_preparation_definition_monthly: &ORCHESTRATOR_CACHE_MONTHLY
  set_orchestrator_home_script: |
    export THIS_MONTH=$(date '+%Y-%m')
    echo "THIS_MONTH=${THIS_MONTH}" >> $CIRRUS_ENV
    echo "ORCHESTRATOR_HOME=${CIRRUS_WORKING_DIR}/orchestrator/${THIS_MONTH}" >> $CIRRUS_ENV
  mkdir_orchestrator_home_script: |
    echo "Create dir ${ORCHESTRATOR_HOME} if needed"
    mkdir -p ${ORCHESTRATOR_HOME}
  orchestrator_cache:
    folder: ${ORCHESTRATOR_HOME}
    fingerprint_script: echo ${THIS_MONTH}
    reupload_on_changes: 'true'

orchestrator_cache_preparation_definition: &ORCHESTRATOR_CACHE
  set_orchestrator_home_script: |
    export TODAY=$(date '+%Y-%m-%d')
    echo "TODAY=${TODAY}" >> $CIRRUS_ENV
    echo "ORCHESTRATOR_HOME=${CIRRUS_WORKING_DIR}/orchestrator/${TODAY}" >> $CIRRUS_ENV
  mkdir_orchestrator_home_script: |
    echo "Create dir ${ORCHESTRATOR_HOME} if needed"
    mkdir -p ${ORCHESTRATOR_HOME}
  orchestrator_cache:
    folder: ${ORCHESTRATOR_HOME}
    fingerprint_script: echo ${TODAY}
    reupload_on_changes: 'true'

nodejs_runtimes_cache_definition: &RUNTIME_CACHE
  runtime_cache:
    folder: sonar-plugin/sonar-javascript-plugin/downloads/
    fingerprint_script: cat sonar-plugin/sonar-javascript-plugin/pom.xml | grep -o "<nodeVersion>.*"

npm_cache_definition: &NPM_CACHE
  npm_cache:
    folder: ${CIRRUS_WORKING_DIR}/node_modules
    fingerprint_script: cat package-lock.json

js_coverage_cache_definition: &JS_COVERAGE_CACHE
  js_coverage_cache:
    folder: ${CIRRUS_WORKING_DIR}/coverage/js
    fingerprint_script: echo "JS$(git rev-parse HEAD)"
    reupload_on_changes: 'true'

java_coverage_cache_definition: &JAVA_COVERAGE_CACHE
  java_coverage_cache:
    folder: ${CIRRUS_WORKING_DIR}/coverage/java
    fingerprint_script: echo "JAVA$(git rev-parse HEAD)"
    reupload_on_changes: 'true'

win_vm_definition: &WINDOWS_VM_DEFINITION
  ec2_instance:
    experimental: true # see https://github.com/cirruslabs/cirrus-ci-docs/issues/1051
    image: base-windows-jdk17-v*
    platform: windows
    region: eu-central-1
    type: c6id.4xlarge
    preemptible: false
    use_ssd: true

npmrc_script_definition: &NPMRC_SCRIPT_DEFINITION
  npmrc_script:
    - cp .cirrus/npmrc $CIRRUS_WORKING_DIR/.npmrc
    - cp .cirrus/npmrc $CIRRUS_WORKING_DIR/packages/jsts/src/rules/.npmrc
    - cp .cirrus/npmrc $CIRRUS_WORKING_DIR/its/eslint8-plugin-sonarjs/.npmrc
    - cp .cirrus/npmrc $CIRRUS_WORKING_DIR/its/eslint9-plugin-sonarjs/.npmrc

win_ssd_and_clone:
  &WIN_SSD_AND_CLONE # copy&paste from https://github.com/SonarSource/sonar-cpp/blob/a8c6f1e45a12393508682a013ac7ee35eb92bece/.cirrus.yml#L45
  prepare_disk_script:
    - ps: |
        Get-Disk -Number 2 | Initialize-Disk -PassThru | New-Partition -UseMaximumSize -DriveLetter Z
        Format-Volume -DriveLetter Z -FileSystem NTFS -Confirm:$false
    - echo "CIRRUS_WORKING_DIR=Z:/cirrus-ci-build" >> $CIRRUS_ENV
  # we don't clone submodules because they are not needed for the tests
  clone_script: |
    git config --system core.longpaths true
    if [ -z "$CIRRUS_PR" ]; then
      git clone --branch=$CIRRUS_BRANCH https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
      git reset --hard $CIRRUS_CHANGE_IN_REPO
    else
      git clone https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
      git fetch origin pull/$CIRRUS_PR/head:pull/$CIRRUS_PR
      git reset --hard $CIRRUS_CHANGE_IN_REPO
    fi

only_sonarsource_qa: &ONLY_SONARSOURCE_QA
  only_if: $CIRRUS_USER_COLLABORATOR == 'true' && ($CIRRUS_PR != "" || $CIRRUS_BRANCH == "master" || $CIRRUS_BRANCH =~ "branch-.*" || $CIRRUS_BRANCH =~ "dogfood-on-.*")

plugin_qa_body: &PLUGIN_QA_BODY
  depends_on:
    - build
  <<: *ONLY_SONARSOURCE_QA
  eks_container:
    <<: *CONTAINER_DEFINITION
  env:
    CIRRUS_CLONE_DEPTH: 10
    SONARSOURCE_QA: true
  <<: *MAVEN_CACHE
  <<: *ORCHESTRATOR_CACHE
  qa_script:
    - source cirrus-env QA
    - source set_maven_build_version $BUILD_NUMBER
    - mvn -f its/plugin/pom.xml -DskipTests=false -Dsonar.runtimeVersion=${SQ_VERSION} ${MVN_TEST} -B -e -V verify surefire-report:report

plugin_qa_body_monthly: &PLUGIN_QA_BODY_MONTHLY
  depends_on:
    - build
  <<: *ONLY_SONARSOURCE_QA
  eks_container:
    <<: *CONTAINER_DEFINITION
  env:
    CIRRUS_CLONE_DEPTH: 10
    SONARSOURCE_QA: true
  <<: *MAVEN_CACHE
  <<: *ORCHESTRATOR_CACHE_MONTHLY
  qa_script:
    - source cirrus-env QA
    - source set_maven_build_version $BUILD_NUMBER
    - mvn -f its/plugin/pom.xml -DskipTests=false -Dsonar.runtimeVersion=${SQ_VERSION} ${MVN_TEST} -B -e -V verify surefire-report:report

build_task:
  eks_container:
    <<: *CONTAINER_DEFINITION
    dockerfile: .cirrus/nodejs.Dockerfile
    docker_arguments:
      CIRRUS_AWS_ACCOUNT: ${CIRRUS_AWS_ACCOUNT}
      NODE_VERSION: 22
  env:
    #allow deployment of pull request artifacts to repox
    DEPLOY_PULL_REQUEST: true
    #sign artifacts
    SIGN_KEY: VAULT[development/kv/data/sign data.key]
    PGP_PASSPHRASE: VAULT[development/kv/data/sign data.passphrase]
    SONAR_TOKEN: VAULT[development/kv/data/next data.token]
    SONAR_HOST_URL: https://next.sonarqube.com/sonarqube
    ARTIFACTORY_DEPLOY_ACCESS_TOKEN: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-qa-deployer access_token]
  <<: *MAVEN_CACHE
  <<: *RUNTIME_CACHE
  <<: *NPM_CACHE
  <<: *NPMRC_SCRIPT_DEFINITION
  build_and_deploy_script:
    - source cirrus-env BUILD
    - node --version
    - npm ci
    - regular_mvn_build_deploy_analyze -T1C -Dsonar.skip=true -DartifactoryToken=$ARTIFACTORY_ACCESS_TOKEN -DskipTests

test_js_task:
  eks_container:
    <<: *CONTAINER_DEFINITION
    dockerfile: .cirrus/nodejs.Dockerfile
    docker_arguments:
      CIRRUS_AWS_ACCOUNT: ${CIRRUS_AWS_ACCOUNT}
      NODE_VERSION: 22
  depends_on:
    - build
  <<: *NPM_CACHE
  <<: *NPMRC_SCRIPT_DEFINITION
  <<: *JS_COVERAGE_CACHE
  test_js_script:
    - source cirrus-env QA
    - npm run generate-meta
    - npm run bridge:build:fast
    - npm run bridge:test:cov

test_java_task:
  eks_container:
    <<: *CONTAINER_DEFINITION
    dockerfile: .cirrus/nodejs.Dockerfile
    docker_arguments:
      CIRRUS_AWS_ACCOUNT: ${CIRRUS_AWS_ACCOUNT}
      NODE_VERSION: 22
  depends_on:
    - build
  <<: *MAVEN_CACHE
  <<: *RUNTIME_CACHE
  <<: *NPM_CACHE
  <<: *NPMRC_SCRIPT_DEFINITION
  <<: *JAVA_COVERAGE_CACHE
  test_java_script:
    - source cirrus-env QA
    - mvn install -T1C -Pcoverage,coverage-report

analyze_task:
  eks_container:
    <<: *CONTAINER_DEFINITION
    dockerfile: .cirrus/nodejs.Dockerfile
    docker_arguments:
      CIRRUS_AWS_ACCOUNT: ${CIRRUS_AWS_ACCOUNT}
      NODE_VERSION: 22
  depends_on:
    - test_js
    - test_java
  env:
    # analysis on next
    SONAR_TOKEN: VAULT[development/kv/data/next data.token]
    SONAR_HOST_URL: https://next.sonarqube.com/sonarqube
  <<: *MAVEN_CACHE
  <<: *RUNTIME_CACHE
  <<: *NPM_CACHE
  <<: *NPMRC_SCRIPT_DEFINITION
  <<: *JS_COVERAGE_CACHE
  <<: *JAVA_COVERAGE_CACHE
  analyze_script:
    - source cirrus-env BUILD
    - PULL_REQUEST_SHA=$GIT_SHA1 regular_mvn_build_deploy_analyze -P-deploy-sonarsource,-release,-sign -Dcommercial -Dmaven.shade.skip=true -Dmaven.install.skip=true -Dmaven.deploy.skip=true -DskipTests

build_win_task:
  <<: *WINDOWS_VM_DEFINITION
  <<: *ONLY_SONARSOURCE_QA
  <<: *MAVEN_CACHE
  <<: *RUNTIME_CACHE
  <<: *NPMRC_SCRIPT_DEFINITION
  build_script:
    - source cirrus-env BUILD
    - npm ci
    - mvn clean install -e

ws_scan_task:
  depends_on:
    - build
  eks_container:
    <<: *CONTAINER_DEFINITION
    dockerfile: .cirrus/nodejs.Dockerfile
    docker_arguments:
      CIRRUS_AWS_ACCOUNT: ${CIRRUS_AWS_ACCOUNT}
    cpu: 4
    memory: 8G
  # run only on master and long-term branches
  only_if: $CIRRUS_USER_COLLABORATOR == 'true' && ($CIRRUS_BRANCH == "master" || $CIRRUS_BRANCH =~ "branch-.*")
  env:
    WS_APIKEY: VAULT[development/kv/data/mend data.apikey]
  <<: *MAVEN_CACHE
  <<: *NPM_CACHE
  <<: *NPMRC_SCRIPT_DEFINITION
  whitesource_script:
    - source cirrus-env QA
    - source set_maven_build_version $BUILD_NUMBER
    - npm ci
    - source ws_scan.sh
  allow_failures: 'true'
  always:
    ws_artifacts:
      path: 'whitesource/**/*'

plugin_qa_with_node_task:
  <<: *PLUGIN_QA_BODY_MONTHLY
  eks_container:
    dockerfile: .cirrus/nodejs.Dockerfile
  env:
    SQ_VERSION: LATEST_RELEASE
    MVN_TEST: ''

plugin_qa_no_node_task:
  <<: *PLUGIN_QA_BODY_MONTHLY
  eks_container:
    image: ${CIRRUS_AWS_ACCOUNT}.dkr.ecr.eu-central-1.amazonaws.com/base:j17-latest
  env:
    SQ_VERSION: LATEST_RELEASE
    SONARJS_ARTIFACT: multi
    MVN_TEST: '-Dtest=!EslintCustomRulesTest,!SonarJsIntegrationTest --projects !org.sonarsource.javascript:eslint-custom-rules-plugin'

plugin_qa_no_node_alpine_task:
  <<: *PLUGIN_QA_BODY_MONTHLY
  eks_container:
    dockerfile: .cirrus/alpine.Dockerfile
  env:
    SQ_VERSION: LATEST_RELEASE
    SONARJS_ARTIFACT: linux-x64-musl
    MVN_TEST: '-Dtest=!EslintCustomRulesTest,!SonarJsIntegrationTest --projects !org.sonarsource.javascript:eslint-custom-rules-plugin'

plugin_qa_sq_dev_task:
  <<: *PLUGIN_QA_BODY
  eks_container:
    image: ${CIRRUS_AWS_ACCOUNT}.dkr.ecr.eu-central-1.amazonaws.com/base:j17-latest
  env:
    SQ_VERSION: 'DEV'
    SONARJS_ARTIFACT: multi
    MVN_TEST: '-Dtest=!EslintCustomRulesTest,!SonarJsIntegrationTest --projects !org.sonarsource.javascript:eslint-custom-rules-plugin'

# Plugin QA for Windows is split into 3 parts to make it faster
plugin_qa_win_task:
  depends_on:
    - build
  <<: *WINDOWS_VM_DEFINITION
  <<: *ONLY_SONARSOURCE_QA
  env:
    SONARSOURCE_QA: true
    SQ_VERSION: LATEST_RELEASE
    matrix:
      - TEST: '!CoverageTest,!TypeScriptAnalysisTest,!EslintBasedRulesTest,!PRAnalysisTest,!TypeCheckerConfigTest,!VueAnalysisTest'
      - TEST: 'CoverageTest,TypeScriptAnalysisTest,EslintBasedRulesTest,PRAnalysisTest,TypeCheckerConfigTest,VueAnalysisTest'
  <<: *WIN_SSD_AND_CLONE
  <<: *MAVEN_CACHE
  <<: *ORCHESTRATOR_CACHE_MONTHLY
  qa_script:
    - source /c/buildTools-docker/bin/cirrus-env QA
    - source /c/buildTools-docker/bin/set_maven_build_version $BUILD_NUMBER
    # building the custom plugin required for the further tests
    - mvn clean package -f its/plugin/plugins/pom.xml
    - mvn test -f its/plugin/tests/pom.xml -DskipTests=false -Dsonar.runtimeVersion=${SQ_VERSION} "-Dtest=${TEST}" -B -e -V surefire-report:report

# Plugin QA for Windows is split into 3 parts to make it faster
plugin_qa_win_sonarlint_task:
  depends_on:
    - build
  <<: *WINDOWS_VM_DEFINITION
  <<: *ONLY_SONARSOURCE_QA
  env:
    SONARSOURCE_QA: true
    SQ_VERSION: LATEST_RELEASE
  <<: *WIN_SSD_AND_CLONE
  <<: *MAVEN_CACHE
  qa_script:
    - source /c/buildTools-docker/bin/cirrus-env QA
    - source /c/buildTools-docker/bin/set_maven_build_version $BUILD_NUMBER
    - mvn test -f its/plugin/sonarlint-tests/pom.xml -DskipTests=false -Dsonar.runtimeVersion=${SQ_VERSION} -B -e -V surefire-report:report

js_ts_ruling_task:
  depends_on:
    - build
  <<: *ONLY_SONARSOURCE_QA
  eks_container:
    <<: *CONTAINER_DEFINITION
    dockerfile: .cirrus/nodejs.Dockerfile
    docker_arguments:
      CIRRUS_AWS_ACCOUNT: ${CIRRUS_AWS_ACCOUNT}
      NODE_VERSION: 22
  env:
    CIRRUS_CLONE_DEPTH: 1
    SONARSOURCE_QA: true
  <<: *MAVEN_CACHE
  <<: *NPM_CACHE
  <<: *NPMRC_SCRIPT_DEFINITION
  # needed because we need to build the plugin
  <<: *RUNTIME_CACHE
  submodules_script:
    - git submodule update --init
  ruling_script:
    - . ~/.profile
    - source cirrus-env QA
    - source set_maven_build_version $BUILD_NUMBER
    - npm run build:fast
    - npm run ruling
  on_failure:
    debug_script: diff -rq its/ruling/src/test/expected/jsts packages/ruling/tests/actual/jsts

eslint_plugin_test_task:
  depends_on:
    - build
  eks_container:
    <<: *CONTAINER_DEFINITION
    dockerfile: .cirrus/nodejs.Dockerfile
    docker_arguments:
      CIRRUS_AWS_ACCOUNT: ${CIRRUS_AWS_ACCOUNT}
  env:
    CIRRUS_CLONE_DEPTH: 1
    SONARSOURCE_QA: true
  <<: *MAVEN_CACHE
  <<: *NPM_CACHE
  <<: *NPMRC_SCRIPT_DEFINITION
  # needed because we need to build the plugin
  <<: *RUNTIME_CACHE
  eslint_its_script:
    - node --version
    - . ~/.profile
    - source cirrus-env QA
    - source set_maven_build_version $BUILD_NUMBER
    - npm run eslint-plugin:build
    - cd its/eslint8-plugin-sonarjs
    - npm install
    - npx tsc --noEmit # check typings for tseslint.config.ts
    - npm run test
    - cd ../eslint9-plugin-sonarjs
    - npm install
    - npx tsc --noEmit # check typings for tseslint.config.ts
    - npm run test

eslint8_node16_plugin_test_task:
  depends_on:
    - build
  eks_container:
    <<: *CONTAINER_DEFINITION
    dockerfile: .cirrus/nodejs16.Dockerfile
    docker_arguments:
      CIRRUS_AWS_ACCOUNT: ${CIRRUS_AWS_ACCOUNT}
  env:
    CIRRUS_CLONE_DEPTH: 1
    SONARSOURCE_QA: true
  <<: *MAVEN_CACHE
  <<: *NPM_CACHE
  <<: *NPMRC_SCRIPT_DEFINITION
  # needed because we need to build the plugin
  <<: *RUNTIME_CACHE
  eslint_its_script:
    - node --version
    - . ~/.profile
    - source cirrus-env QA
    - source set_maven_build_version $BUILD_NUMBER
    - npm run eslint-plugin:build
    - cd its/eslint8-plugin-sonarjs
    - npm install
    - npx tsc --noEmit # check typings for tseslint.config.ts
    - npm run test

css_ruling_task:
  depends_on:
    - build
  <<: *ONLY_SONARSOURCE_QA
  eks_container:
    <<: *CONTAINER_DEFINITION
    image: ${CIRRUS_AWS_ACCOUNT}.dkr.ecr.eu-central-1.amazonaws.com/base:j17-latest
  env:
    CIRRUS_CLONE_DEPTH: 10
    SONARSOURCE_QA: true
  <<: *MAVEN_CACHE
  <<: *ORCHESTRATOR_CACHE_MONTHLY
  submodules_script:
    - git submodule update --init
  ruling_script:
    - source cirrus-env QA
    - source set_maven_build_version $BUILD_NUMBER
    - cd its/ruling
    - mvn test -DskipTests=false -Dtest=CssRulingTest -Dsonar.runtimeVersion=LATEST_RELEASE -Dmaven.test.redirectTestOutputToFile=false -Djunit.jupiter.execution.parallel.config.dynamic.factor=1 -B -e -V
  on_failure:
    diff_artifacts:
      path: '**/target/actual/**/*'

promote_task:
  depends_on:
    - ws_scan
    - build_win
    - plugin_qa_with_node
    - plugin_qa_no_node
    - plugin_qa_no_node_alpine
    - plugin_qa_sq_dev
    - plugin_qa_win
    - plugin_qa_win_sonarlint
    - css_ruling
    - js_ts_ruling
    - analyze
  <<: *ONLY_SONARSOURCE_QA
  eks_container:
    <<: *CONTAINER_DEFINITION
    image: ${CIRRUS_AWS_ACCOUNT}.dkr.ecr.eu-central-1.amazonaws.com/base:j17-latest
    cpu: 2
    memory: 4G
  env:
    ARTIFACTORY_PROMOTE_ACCESS_TOKEN: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-promoter access_token]
    GITHUB_TOKEN: VAULT[development/github/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-promotion token]
  <<: *MAVEN_CACHE
  script: cirrus_promote_maven
