# Definition of QA pipeline at SonarSource
#
# Possible values for SLAVE: "performance" (for perf tests) and "linux" (for linux machines connected to DB services)

TEST:
  - plugin
  - ruling
  - performancing

SQ_VERSION: 
  - DEV
  - 6.2
  - LTS


exclude:
  - TEST: plugin
    SLAVE: linux
    SQ_VERSION: 6.2

  - SLAVE: linux 
    SQ_VERSION: DEV 
    TEST: ruling

  - SLAVE: linux
    SQ_VERSION: LTS 
    TEST: ruling

#remove all jobs on performance slave
  - TEST: plugin
    SLAVE: performance
    SQ_VERSION: 6.2

  - SLAVE: performance 
    SQ_VERSION: DEV 
    TEST: ruling

  - SLAVE: performance
    SQ_VERSION: LTS 
    TEST: ruling

  - SLAVE: performance
    SQ_VERSION: DEV 
    TEST: plugin

  - SLAVE: performance
    SQ_VERSION: 6.2 
    TEST: ruling

  - SLAVE: performance
    SQ_VERSION: LTS 
    TEST: plugin

#remove all jobs on windows slave plugin on 6.2
  - SLAVE: windows 
    SQ_VERSION: DEV 
    TEST: ruling

  - SLAVE: windows
    SQ_VERSION: LTS 
    TEST: ruling

  - SLAVE: windows
    SQ_VERSION: DEV 
    TEST: plugin

  - SLAVE: windows
    SQ_VERSION: 6.2 
    TEST: ruling

  - SLAVE: windows
    SQ_VERSION: LTS 
    TEST: plugin

# only run performancing on DEV 6.2 on performance Slave
  - SLAVE: performance
    SQ_VERSION: LTS 
    TEST: performancing

  - SLAVE: performance
    SQ_VERSION: DEV
    TEST: performancing

  - SLAVE: linux
    SQ_VERSION: LTS 
    TEST: performancing

  - SLAVE: linux
    SQ_VERSION: DEV
    TEST: performancing

  - SLAVE: linux
    SQ_VERSION: 6.2
    TEST: performancing

  - SLAVE: windows
    SQ_VERSION: LTS 
    TEST: performancing 

  - SLAVE: windows
    SQ_VERSION: DEV
    TEST: performancing          

  - SLAVE: windows
    SQ_VERSION: 6.2
    TEST: performancing 
