sources = [
  "packages/*/src/**/*.ts"
]

excludedSources = [
  "packages/**/*.test.*",
  "packages/**/*.fixture.*",
  "packages/**/fixtures/**",
  "packages/jsts/src/rules/plugin-rules.ts",
  "packages/jsts/src/rules/rules.ts",
  "packages/jsts/src/rules/metas.ts",
]

coverageDirectory="coverage/.coverage" # this should not be cached in CI
reportsDirectory="coverage/js/"

reporters = [
  "lcovonly",
  "text-summary",
]
