#!/usr/bin/env bash
# MIT License © Sindre Sorhus
# Modified for Deno

if [[ -z $RUN_DENO_CACHE_PATH ]]; then
	PATH_CACHE="$HOME"/.deno_path
else
	PATH_CACHE="$RUN_DENO_CACHE_PATH"
	if [[ -f "$PATH_CACHE" ]]; then
		. "$PATH_CACHE"
		export PATH
	fi
fi

get_user_path() {
	[[ -x "/usr/libexec/path_helper" ]] && eval $(/usr/libexec/path_helper -s)
	echo "$($SHELL -i -l -c 'echo -e "\n"PATH=\"$PATH:\$PATH\""\n"' 2>/dev/null | grep "^PATH=")" > "$PATH_CACHE"
}

set_path() {
	if [[ -f "$PATH_CACHE" ]]; then
		. "$PATH_CACHE"
	else
		get_user_path
		. "$PATH_CACHE"
	fi

	export PATH
}

has_deno() {
	command -v deno >/dev/null 2>&1
}

if ! has_deno; then
	set_path

	# Retry by deleting old path cache
	if ! has_deno; then
		rm -f "$PATH_CACHE"
		set_path
	fi
fi

if has_deno; then
	deno "$@"
else
	if [[ -z $RUN_DENO_ERROR_MSG ]]; then
		echo "Couldn't find the Deno binary. Ensure you have Deno installed: https://deno.land/#installation"
	else
		echo "$RUN_DENO_ERROR_MSG"
	fi
fi
