/*
 * SonarQube JavaScript Plugin
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */
// https://sonarsource.github.io/rspec/#/rspec/S8686/javascript

// DO NOT EDIT! This file is autogenerated by "npm run generate-meta"

import type { SonarMeta } from '../helpers/generate-meta.js';
export * from './meta.js';

export const meta = {
  type: 'suggestion',
  docs: {
    description: 'Assertions should not be conditional',
    recommended: true,
    url: 'https://sonarsource.github.io/rspec/#/rspec/S8686/javascript',
    requiresTypeChecking: false,
  },
  fixable: undefined,
  deprecated: false,
  defaultOptions: [],
} satisfies SonarMeta['meta'];

export const sonarKey = 'S8686';
export const scope = 'Tests';
export const languages: ('js' | 'ts')[] = ['js', 'ts'];
export const requiredDependency = [];
export const skipOnGeneratedSource = false;
