// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package no_misused_promises

import "github.com/go-json-experiment/json"

type ChecksVoidReturnOptions struct {
	// Arguments corresponds to the JSON schema field "arguments".
	Arguments bool `json:"arguments,omitempty"`

	// Attributes corresponds to the JSON schema field "attributes".
	Attributes bool `json:"attributes,omitempty"`

	// InheritedMethods corresponds to the JSON schema field "inheritedMethods".
	InheritedMethods bool `json:"inheritedMethods,omitempty"`

	// Properties corresponds to the JSON schema field "properties".
	Properties bool `json:"properties,omitempty"`

	// Returns corresponds to the JSON schema field "returns".
	Returns bool `json:"returns,omitempty"`

	// Variables corresponds to the JSON schema field "variables".
	Variables bool `json:"variables,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ChecksVoidReturnOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain ChecksVoidReturnOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["arguments"]; !ok || v == nil {
		plain.Arguments = true
	}
	if v, ok := raw["attributes"]; !ok || v == nil {
		plain.Attributes = true
	}
	if v, ok := raw["inheritedMethods"]; !ok || v == nil {
		plain.InheritedMethods = true
	}
	if v, ok := raw["properties"]; !ok || v == nil {
		plain.Properties = true
	}
	if v, ok := raw["returns"]; !ok || v == nil {
		plain.Returns = true
	}
	if v, ok := raw["variables"]; !ok || v == nil {
		plain.Variables = true
	}
	*j = ChecksVoidReturnOptions(plain)
	return nil
}

type NoMisusedPromisesOptions struct {
	// ChecksConditionals corresponds to the JSON schema field "checksConditionals".
	ChecksConditionals bool `json:"checksConditionals,omitempty"`

	// ChecksSpreads corresponds to the JSON schema field "checksSpreads".
	ChecksSpreads bool `json:"checksSpreads,omitempty"`

	// ChecksVoidReturn corresponds to the JSON schema field "checksVoidReturn".
	ChecksVoidReturn interface{} `json:"checksVoidReturn,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NoMisusedPromisesOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain NoMisusedPromisesOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["checksConditionals"]; !ok || v == nil {
		plain.ChecksConditionals = true
	}
	if v, ok := raw["checksSpreads"]; !ok || v == nil {
		plain.ChecksSpreads = true
	}
	if v, ok := raw["checksVoidReturn"]; !ok || v == nil {
		plain.ChecksVoidReturn = true
	}
	*j = NoMisusedPromisesOptions(plain)
	return nil
}
