// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package prefer_readonly

import "github.com/go-json-experiment/json"

type PreferReadonlyOptions struct {
	// Whether to restrict checking only to members immediately assigned a lambda
	// value.
	OnlyInlineLambdas bool `json:"onlyInlineLambdas,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PreferReadonlyOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain PreferReadonlyOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["onlyInlineLambdas"]; !ok || v == nil {
		plain.OnlyInlineLambdas = false
	}
	*j = PreferReadonlyOptions(plain)
	return nil
}
