/*
 * SonarQube JavaScript Plugin
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */
import {
  filterBundle,
  filterBundleCode,
  hasGeneratedHeaderComment,
} from '../../src/common/filter/filter-bundle.js';
import { describe, it } from 'node:test';
import { expect } from 'expect';
import { normalizeToAbsolutePath } from '../../../shared/src/helpers/files.js';

describe('filter bundle', () => {
  it('should return true for a bundle file', () => {
    const BUNDLE_CONTENTS = '/* jQuery JavaScript Library v1.4.3*/(function(';
    expect(filterBundle(normalizeToAbsolutePath('/test.ts'), BUNDLE_CONTENTS)).toBeFalsy();
  });
  it('should return false for a non-bundled file', () => {
    const CONTENTS = 'contents';
    expect(filterBundle(normalizeToAbsolutePath('/test.ts'), CONTENTS)).toBeTruthy();
  });
});

describe('filterBundleCode', () => {
  it('should return false for jQuery-style bundle', () => {
    const bundleCode = '/* jQuery JavaScript Library v1.4.3*/(function(';
    expect(filterBundleCode(bundleCode)).toBe(false);
  });

  it('should return false for minified bundle with exclamation mark', () => {
    const bundleCode = '/*! jQuery v3.5.1 | (c) JS Foundation */!function(e,t){"use strict";}';
    expect(filterBundleCode(bundleCode)).toBe(false);
  });

  it('should return false for bundle with semicolon operator', () => {
    const bundleCode = '/* bundle */;function test(){}';
    expect(filterBundleCode(bundleCode)).toBe(false);
  });

  it('should return false for bundle with plus operator', () => {
    const bundleCode = '/* bundle */+function(){}';
    expect(filterBundleCode(bundleCode)).toBe(false);
  });

  it('should return false for bundle with parenthesis operator', () => {
    const bundleCode = '/* bundle */(function(){}';
    expect(filterBundleCode(bundleCode)).toBe(false);
  });

  it('should return true for normal code', () => {
    const normalCode = 'function hello() { console.log("hello"); }';
    expect(filterBundleCode(normalCode)).toBe(true);
  });

  it('should return true for code with comment but no bundle pattern', () => {
    const normalCode = '/* This is a comment */ const x = 1;';
    expect(filterBundleCode(normalCode)).toBe(true);
  });

  it('should return true for empty code', () => {
    expect(filterBundleCode('')).toBe(true);
  });
});

describe('hasGeneratedHeaderComment', () => {
  it('should detect @generated in a leading block comment', () => {
    const code = `/**
 * @generated
 */
export const value = 1;`;
    expect(hasGeneratedHeaderComment(code)).toBe(true);
  });

  it('should detect @auto-generated in a leading line comment', () => {
    const code = `// @auto-generated
// generated by a tool
export const value = 1;`;
    expect(hasGeneratedHeaderComment(code)).toBe(true);
  });

  it('should detect DO NOT EDIT in a leading header comment', () => {
    const code = `// DO NOT EDIT! This file is autogenerated by a tool
export const value = 1;`;
    expect(hasGeneratedHeaderComment(code)).toBe(true);
  });

  it('should detect Generated by in a leading header comment', () => {
    const code = `/*
 * Generated by JsPbCodeGenerator.
 */
export const value = 1;`;
    expect(hasGeneratedHeaderComment(code)).toBe(true);
  });

  it('should ignore generated by in descriptive prose inside a leading header comment', () => {
    const code = `/**
 * Script that detects and validates entry-points.
 * The list is passed through a manifest file (generated by Bazel).
 */
export const value = 1;`;
    expect(hasGeneratedHeaderComment(code)).toBe(false);
  });

  it('should ignore generated by in later sentences of a doc comment', () => {
    const code = `/**
 * A transition can be retried and new transitions can be generated by calling retry.
 */
export const value = 1;`;
    expect(hasGeneratedHeaderComment(code)).toBe(false);
  });

  it('should detect SignedSource generated marker in a leading header comment', () => {
    const code = `/**
 * @generated SignedSource<<1234567890>>
 */
"use strict";`;
    expect(hasGeneratedHeaderComment(code)).toBe(true);
  });

  it('should ignore generated markers that only appear later in code', () => {
    const code = `export const text = "Generated by create-t3-app";
// @generated`;
    expect(hasGeneratedHeaderComment(code)).toBe(false);
  });

  it('should ignore regular leading comments without generated markers', () => {
    const code = `/*
 * Copyright (c) Example
 */
export const value = 1;`;
    expect(hasGeneratedHeaderComment(code)).toBe(false);
  });

  it('should detect markers after a shebang', () => {
    const code = `#!/usr/bin/env node
// DO NOT EDIT
console.log("hello");`;
    expect(hasGeneratedHeaderComment(code)).toBe(true);
  });
});
