name: Setup Maven Cache
description: Sets up Maven cache with restore-only behavior on non-default branches

inputs:
  cache-month:
    description: 'Month string for cache key rotation (YYYY-MM)'
    required: true
  maven-hash:
    description: 'Hash of pom.xml files for cache key'
    required: true

runs:
  using: composite
  steps:
    # Restore only on branches (no save) - allows branches to read from default branch's cache
    - name: Restore Maven cache (branches)
      if: github.ref_name != github.event.repository.default_branch
      uses: actions/cache/restore@v5
      with:
        path: |
          ~/.m2/repository
          !~/.m2/repository/org/sonarsource/javascript
        key: maven-${{ runner.os }}-${{ inputs.cache-month }}-${{ inputs.maven-hash }}
        restore-keys: maven-${{ runner.os }}-${{ inputs.cache-month }}-

    # Full cache on default branch (save enabled)
    # Note: Exclusion patterns don't work reliably with runs-on/cache used by gh-action_cache.
    # Instead, we clean up SonarJS artifacts at the end of the job before post-job cache save.
    - name: Cache Maven dependencies (default branch)
      if: github.ref_name == github.event.repository.default_branch
      uses: SonarSource/gh-action_cache@v1
      with:
        path: ~/.m2/repository
        key: maven-${{ runner.os }}-${{ inputs.cache-month }}-${{ inputs.maven-hash }}
        restore-keys: maven-${{ runner.os }}-${{ inputs.cache-month }}-

    # Clean up any SonarJS artifacts that were restored from cache
    - name: Remove restored SonarJS artifacts
      shell: bash
      run: rm -rf ~/.m2/repository/org/sonarsource/javascript
