/*
 * SonarQube JavaScript Plugin
 * Copyright (C) 2011-2025 SonarSource SA
 * mailto:info AT sonarsource DOT com
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the Sonar Source-Available License Version 1, as published by SonarSource SA.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

// DO NOT EDIT! This file is autogenerated by "npm run generate-meta"

package org.sonar.javascript.checks;

import java.util.List;
import java.util.Map;
import org.sonar.check.Rule;
import org.sonar.check.RuleProperty;
import org.sonar.plugins.javascript.api.Check;
import org.sonar.plugins.javascript.api.JavaScriptRule;
import org.sonar.plugins.javascript.api.TypeScriptRule;

@JavaScriptRule
@TypeScriptRule
@Rule(key = "S1192")
public class S1192 extends Check {

  @RuleProperty(
    key = "threshold",
    description = "Number of times a literal must be duplicated to trigger an issue.",
    defaultValue = "" + 3
  )
  int threshold = 3;

  @RuleProperty(
    key = "ignoreStrings",
    description = "Comma-separated list of strings that must be ignored.",
    defaultValue = "application/json"
  )
  String ignoreStrings = "application/json";

  @Override
  public List<Object> configurations() {
    return List.of(Map.of("threshold", threshold, "ignoreStrings", ignoreStrings));
  }
}
