/*
 * SonarQube JavaScript Plugin
 * Copyright (C) 2011-2025 SonarSource SA
 * mailto:info AT sonarsource DOT com
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the Sonar Source-Available License Version 1, as published by SonarSource SA.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */
package org.sonar.javascript.checks;

import java.util.List;
import java.util.Map;
// DO NOT EDIT! This file is autogenerated by "npm run generate-meta"

import org.sonar.check.Rule;
import org.sonar.check.RuleProperty;
import org.sonar.plugins.javascript.api.Check;
import org.sonar.plugins.javascript.api.JavaScriptRule;
import org.sonar.plugins.javascript.api.TypeScriptRule;

@JavaScriptRule
@TypeScriptRule
@Rule(key = "S124")
public class S124 extends Check {

  @RuleProperty(
    key = "regularExpression",
    description = "The regular expression (JavaScript syntax)",
    defaultValue = ""
  )
  String regularExpression = "";

  @RuleProperty(
    key = "message",
    description = "The issue message",
    defaultValue = "The regular expression matches this comment."
  )
  String message = "The regular expression matches this comment.";

  @RuleProperty(key = "flags", description = "Regular expression modifier flags", defaultValue = "")
  String flags = "";

  @Override
  public List<Object> configurations() {
    return List.of(
      Map.of("regularExpression", regularExpression, "message", message, "flags", flags)
    );
  }
}
