/*
 * SonarQube JavaScript Plugin
 * Copyright (C) 2011-2024 SonarSource SA
 * mailto:info AT sonarsource DOT com
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the Sonar Source-Available License Version 1, as published by SonarSource SA.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */
// DO NOT EDIT! This file is autogenerated by "npm run generate-meta"

export const meta = {
  type: 'suggestion',
  docs: {
    description: 'Expressions should not be too complex',
    recommended: false,
    url: 'https://sonarsource.github.io/rspec/#/rspec/S1067/javascript',
    requiresTypeChecking: false,
  },
};

export const sonarKey = 'S1067';
import { JSONSchema4 } from '@typescript-eslint/utils/json-schema';
export const schema = {
  type: 'array',
  minItems: 0,
  maxItems: 2,
  items: [
    {
      type: 'object',
      properties: {
        max: {
          type: 'integer',
        },
      },
      additionalProperties: false,
    },
  ],
} as const satisfies JSONSchema4;
