/*
 * SonarQube JavaScript Plugin
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

// DO NOT EDIT! This file is autogenerated by "npm run generate-meta"

package org.sonar.css.rules;

import static org.sonar.css.rules.RuleUtils.splitAndTrim;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import org.sonar.check.Rule;
import org.sonar.check.RuleProperty;
import org.sonar.plugins.javascript.bridge.StylelintRule;

@Rule(key = "S1874")
public class S1874 implements CssRule {

  @RuleProperty(
    key = "ignoreSelectors",
    description = "Comma-separated list of selector names and/or regular expressions to ignore.",
    defaultValue = ""
  )
  String ignoreSelectors = "";

  @RuleProperty(
    key = "ignoreKeywords",
    description = "Comma-separated list of strings and/or regular expressions for deprecated keywords to ignore.",
    defaultValue = ""
  )
  String ignoreKeywords = "";

  @RuleProperty(
    key = "ignoreAtRules",
    description = "Comma-separated list of deprecated \"at-rules\" to ignore.",
    defaultValue = ""
  )
  String ignoredAtRules = "";

  @Override
  public List<StylelintRule> stylelintRules() {
    return Arrays.asList(
      new StylelintRule(
        "selector-no-deprecated",
        toOptions(
          splitAndTrim(ignoreSelectors),
          new IgnoreSelectorsIgnoreOption(splitAndTrim(ignoreSelectors))
        )
      ),
      new StylelintRule(
        "declaration-property-value-keyword-no-deprecated",
        toOptions(
          splitAndTrim(ignoreKeywords),
          new IgnoreKeywordsIgnoreOption(splitAndTrim(ignoreKeywords))
        )
      ),
      new StylelintRule(
        "at-rule-no-deprecated",
        toOptions(
          splitAndTrim(ignoredAtRules),
          new IgnoreAtRulesIgnoreOption(splitAndTrim(ignoredAtRules))
        )
      )
    );
  }

  private static List<Object> toOptions(List<String> values, Object ignoreOption) {
    return values.isEmpty() ? Collections.emptyList() : Arrays.asList(true, ignoreOption);
  }

  private static class IgnoreSelectorsIgnoreOption {

    // Used by GSON serialization
    private final List<String> ignoreSelectors;

    IgnoreSelectorsIgnoreOption(List<String> ignoreSelectors) {
      this.ignoreSelectors = ignoreSelectors;
    }
  }

  private static class IgnoreKeywordsIgnoreOption {

    // Used by GSON serialization
    private final List<String> ignoreKeywords;

    IgnoreKeywordsIgnoreOption(List<String> ignoreKeywords) {
      this.ignoreKeywords = ignoreKeywords;
    }
  }

  private static class IgnoreAtRulesIgnoreOption {

    // Used by GSON serialization
    private final List<String> ignoreAtRules;

    IgnoreAtRulesIgnoreOption(List<String> ignoreAtRules) {
      this.ignoreAtRules = ignoreAtRules;
    }
  }

  @Override
  public String stylelintKey() {
    return "selector-no-deprecated";
  }
}
