// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package no_base_to_string

import "github.com/go-json-experiment/json"

type NoBaseToStringOptions struct {
	// Whether to also check values of type `unknown`.
	CheckUnknown bool `json:"checkUnknown,omitempty"`

	// IgnoredTypeNames corresponds to the JSON schema field "ignoredTypeNames".
	IgnoredTypeNames []string `json:"ignoredTypeNames,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NoBaseToStringOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain NoBaseToStringOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["checkUnknown"]; !ok || v == nil {
		plain.CheckUnknown = false
	}
	if v, ok := raw["ignoredTypeNames"]; !ok || v == nil {
		plain.IgnoredTypeNames = []string{
			"Error",
			"RegExp",
			"URL",
			"URLSearchParams",
		}
	}
	*j = NoBaseToStringOptions(plain)
	return nil
}
