/*
 * SonarQube JavaScript Plugin
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

// DO NOT EDIT! This file is autogenerated by "npm run generate-meta"

package org.sonar.css.rules;

import static org.assertj.core.api.Assertions.assertThat;

import com.google.gson.Gson;
import java.lang.reflect.InvocationTargetException;
import java.util.Set;
import org.junit.jupiter.api.Test;
import org.mockito.internal.util.collections.Sets;
import org.sonar.check.RuleProperty;
import org.sonar.css.CssRules;
import org.sonar.plugins.javascript.bridge.StylelintRule;

class CssRuleTest {

  private static final int RULES_PROPERTIES_COUNT = 13;
  private static final Gson GSON = new Gson();

  @Test
  void class_name_should_match_rule_key()
    throws NoSuchMethodException, IllegalAccessException, InvocationTargetException, InstantiationException {
    for (Class ruleClass : CssRules.getRuleClasses()) {
      org.sonar.check.Rule annotation = (org.sonar.check.Rule) ruleClass.getAnnotation(
        org.sonar.check.Rule.class
      );
      assertThat(ruleClass.getSimpleName()).isEqualTo(annotation.key());
    }
  }

  @Test
  void rules_default_is_empty()
    throws NoSuchMethodException, IllegalAccessException, InvocationTargetException, InstantiationException {
    Set<Class> rulesWithStylelintOptions = Sets.newSet(
      S4649.class,
      S4653.class,
      S4654.class,
      S4656.class,
      S4659.class,
      S4660.class,
      S4662.class,
      S4670.class
    );

    for (Class ruleClass : CssRules.getRuleClasses()) {
      CssRule rule = (CssRule) ruleClass.getConstructor().newInstance();
      if (rulesWithStylelintOptions.contains(rule.getClass())) {
        assertThat(rule.stylelintOptions()).isNotEmpty();
      } else {
        assertThat(rule.stylelintOptions()).isEmpty();
      }
    }
  }

  /*
   * This test raises awareness of the consequence of a rule adding or removing a rule property.
   * If a new rule property is added to an existing rule, we should inform the SonarCloud team
   * about it on release. Rule properties of newly added rules are not concerned by that.
   */
  @Test
  void rules_properties_count() {
    var count = 0;
    for (var clazz : CssRules.getRuleClasses()) {
      for (var field : clazz.getDeclaredFields()) {
        if (field.isAnnotationPresent(RuleProperty.class)) {
          count++;
        }
      }
    }
    assertThat(count).isEqualTo(RULES_PROPERTIES_COUNT);
  }

  @Test
  void s4649_default() {
    String optionsAsJson = GSON.toJson(new S4649().stylelintOptions());
    assertThat(optionsAsJson).isEqualTo("[true,{\"ignoreFontFamilies\":[]}]");
  }

  @Test
  void s4649_custom() {
    S4649 instance = new S4649();
    instance.ignoreFontFamilies = "testValue1, testValue2";
    String optionsAsJson = GSON.toJson(instance.stylelintOptions());
    assertThat(optionsAsJson).isEqualTo(
      "[true,{\"ignoreFontFamilies\":[\"testValue1\",\"testValue2\"]}]"
    );
  }

  @Test
  void s4653_default() {
    String optionsAsJson = GSON.toJson(new S4653().stylelintOptions());
    assertThat(optionsAsJson).isEqualTo(
      "[true,{\"ignoreFunctions\":[\"image-set\",\"spacer\",\"spacing\",\"size\",\"rem\",\"em\",\"fluid\"]}]"
    );
  }

  @Test
  void s4653_custom() {
    S4653 instance = new S4653();
    instance.ignoreFunctions = "testValue1, testValue2";
    String optionsAsJson = GSON.toJson(instance.stylelintOptions());
    assertThat(optionsAsJson).isEqualTo(
      "[true,{\"ignoreFunctions\":[\"testValue1\",\"testValue2\"]}]"
    );
  }

  @Test
  void s4654_default() {
    String optionsAsJson = GSON.toJson(new S4654().stylelintOptions());
    assertThat(optionsAsJson).isEqualTo(
      "[true,{\"ignoreProperties\":[\"composes\",\"/^mso-/\"],\"ignoreSelectors\":[\"/^:export.*/\",\"/^:import.*/\"]}]"
    );
  }

  @Test
  void s4654_custom() {
    S4654 instance = new S4654();
    instance.ignoreProperties = "testValue1, testValue2";
    instance.ignoreSelectors = "testValue1, testValue2";
    String optionsAsJson = GSON.toJson(instance.stylelintOptions());
    assertThat(optionsAsJson).isEqualTo(
      "[true,{\"ignoreProperties\":[\"testValue1\",\"testValue2\"],\"ignoreSelectors\":[\"testValue1\",\"testValue2\"]}]"
    );
  }

  @Test
  void s4656_default() {
    String optionsAsJson = GSON.toJson(new S4656().stylelintOptions());
    assertThat(optionsAsJson).isEqualTo(
      "[true,{\"ignore\":[\"consecutive-duplicates-with-different-values\"]}]"
    );
  }

  @Test
  void s4656_disabled() {
    S4656 instance = new S4656();
    instance.ignoreFallbacks = false;
    assertThat(instance.stylelintOptions()).isEmpty();
  }

  @Test
  void s4659_default() {
    String optionsAsJson = GSON.toJson(new S4659().stylelintOptions());
    assertThat(optionsAsJson).isEqualTo(
      "[true,{\"ignorePseudoClasses\":[\"local\",\"global\",\"export\",\"import\",\"deep\"]}]"
    );
  }

  @Test
  void s4659_custom() {
    S4659 instance = new S4659();
    instance.ignoredPseudoClasses = "testValue1, testValue2";
    String optionsAsJson = GSON.toJson(instance.stylelintOptions());
    assertThat(optionsAsJson).isEqualTo(
      "[true,{\"ignorePseudoClasses\":[\"testValue1\",\"testValue2\"]}]"
    );
  }

  @Test
  void s4660_default() {
    String optionsAsJson = GSON.toJson(new S4660().stylelintOptions());
    assertThat(optionsAsJson).isEqualTo(
      "[true,{\"ignorePseudoElements\":[\"ng-deep\",\"v-deep\",\"deep\"]}]"
    );
  }

  @Test
  void s4660_custom() {
    S4660 instance = new S4660();
    instance.ignorePseudoElements = "testValue1, testValue2";
    String optionsAsJson = GSON.toJson(instance.stylelintOptions());
    assertThat(optionsAsJson).isEqualTo(
      "[true,{\"ignorePseudoElements\":[\"testValue1\",\"testValue2\"]}]"
    );
  }

  @Test
  void s4662_default() {
    String optionsAsJson = GSON.toJson(new S4662().stylelintOptions());
    assertThat(optionsAsJson).isEqualTo(
      "[true,{\"ignoreAtRules\":[\"value\",\"at-root\",\"content\",\"debug\",\"each\",\"else\",\"error\",\"for\",\"function\",\"if\",\"include\",\"mixin\",\"return\",\"warn\",\"while\",\"extend\",\"use\",\"forward\",\"tailwind\",\"apply\",\"layer\",\"container\",\"theme\",\"utility\",\"custom-variant\",\"source\",\"plugin\",\"config\",\"reference\",\"variant\",\"/^@.*/\"]}]"
    );
  }

  @Test
  void s4662_custom() {
    S4662 instance = new S4662();
    instance.ignoredAtRules = "testValue1, testValue2";
    String optionsAsJson = GSON.toJson(instance.stylelintOptions());
    assertThat(optionsAsJson).isEqualTo(
      "[true,{\"ignoreAtRules\":[\"testValue1\",\"testValue2\"]}]"
    );
  }

  @Test
  void s4670_default() {
    String optionsAsJson = GSON.toJson(new S4670().stylelintOptions());
    assertThat(optionsAsJson).isEqualTo(
      "[true,{\"ignoreTypes\":[\"/^(mat|md|fa)-/\"],\"ignore\":[\"custom-elements\"]}]"
    );
  }

  @Test
  void s4670_custom() {
    S4670 instance = new S4670();
    instance.ignoreTypes = "testValue1, testValue2";
    instance.ignore = "testValue1, testValue2";
    String optionsAsJson = GSON.toJson(instance.stylelintOptions());
    assertThat(optionsAsJson).isEqualTo(
      "[true,{\"ignoreTypes\":[\"testValue1\",\"testValue2\"],\"ignore\":[\"testValue1\",\"testValue2\"]}]"
    );
  }

  @Test
  void s1874_bindings_count() {
    assertThat(new S1874().stylelintRules()).hasSize(3);
  }

  @Test
  void s1874_ignoreselectors_empty() {
    StylelintRule sr = new S1874().stylelintRules().get(0);
    assertThat(sr.getKey()).isEqualTo("selector-no-deprecated");
    assertThat(sr.getConfigurations()).isEmpty();
  }

  @Test
  void s1874_ignoreselectors_custom() {
    S1874 instance = new S1874();
    instance.ignoreSelectors = "testValue1, testValue2";
    StylelintRule sr = instance.stylelintRules().get(0);
    assertThat(GSON.toJson(sr.getConfigurations())).isEqualTo(
      "[true,{\"ignoreSelectors\":[\"testValue1\",\"testValue2\"]}]"
    );
  }

  @Test
  void s1874_ignorekeywords_empty() {
    StylelintRule sr = new S1874().stylelintRules().get(1);
    assertThat(sr.getKey()).isEqualTo("declaration-property-value-keyword-no-deprecated");
    assertThat(sr.getConfigurations()).isEmpty();
  }

  @Test
  void s1874_ignorekeywords_custom() {
    S1874 instance = new S1874();
    instance.ignoreKeywords = "testValue1, testValue2";
    StylelintRule sr = instance.stylelintRules().get(1);
    assertThat(GSON.toJson(sr.getConfigurations())).isEqualTo(
      "[true,{\"ignoreKeywords\":[\"testValue1\",\"testValue2\"]}]"
    );
  }

  @Test
  void s1874_ignoredatrules_empty() {
    StylelintRule sr = new S1874().stylelintRules().get(2);
    assertThat(sr.getKey()).isEqualTo("at-rule-no-deprecated");
    assertThat(sr.getConfigurations()).isEmpty();
  }

  @Test
  void s1874_ignoredatrules_custom() {
    S1874 instance = new S1874();
    instance.ignoredAtRules = "testValue1, testValue2";
    StylelintRule sr = instance.stylelintRules().get(2);
    assertThat(GSON.toJson(sr.getConfigurations())).isEqualTo(
      "[true,{\"ignoreAtRules\":[\"testValue1\",\"testValue2\"]}]"
    );
  }
}
