/*
 * SonarQube JavaScript Plugin
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

// DO NOT EDIT! This file was generated by generate-rule-indexes.ts

import { rule as S100 } from './S100/index.js';
import { rule as S101 } from './S101/index.js';
import { rule as S103 } from './S103/index.js';
import { rule as S104 } from './S104/index.js';
import { rule as S105 } from './S105/index.js';
import { rule as S106 } from './S106/index.js';
import { rule as S107 } from './S107/index.js';
import { rule as S108 } from './S108/index.js';
import { rule as S109 } from './S109/index.js';
import { rule as S113 } from './S113/index.js';
import { rule as S117 } from './S117/index.js';
import { rule as S121 } from './S121/index.js';
import { rule as S122 } from './S122/index.js';
import { rule as S124 } from './S124/index.js';
import { rule as S125 } from './S125/index.js';
import { rule as S126 } from './S126/index.js';
import { rule as S128 } from './S128/index.js';
import { rule as S131 } from './S131/index.js';
import { rule as S134 } from './S134/index.js';
import { rule as S135 } from './S135/index.js';
import { rule as S138 } from './S138/index.js';
import { rule as S139 } from './S139/index.js';
import { rule as S878 } from './S878/index.js';
import { rule as S881 } from './S881/index.js';
import { rule as S888 } from './S888/index.js';
import { rule as S905 } from './S905/index.js';
import { rule as S909 } from './S909/index.js';
import { rule as S930 } from './S930/index.js';
import { rule as S1066 } from './S1066/index.js';
import { rule as S1067 } from './S1067/index.js';
import { rule as S1068 } from './S1068/index.js';
import { rule as S1077 } from './S1077/index.js';
import { rule as S1082 } from './S1082/index.js';
import { rule as S1090 } from './S1090/index.js';
import { rule as S1105 } from './S1105/index.js';
import { rule as S1110 } from './S1110/index.js';
import { rule as S1116 } from './S1116/index.js';
import { rule as S1117 } from './S1117/index.js';
import { rule as S1119 } from './S1119/index.js';
import { rule as S1121 } from './S1121/index.js';
import { rule as S1125 } from './S1125/index.js';
import { rule as S1126 } from './S1126/index.js';
import { rule as S1128 } from './S1128/index.js';
import { rule as S1131 } from './S1131/index.js';
import { rule as S1134 } from './S1134/index.js';
import { rule as S1135 } from './S1135/index.js';
import { rule as S1143 } from './S1143/index.js';
import { rule as S1154 } from './S1154/index.js';
import { rule as S1172 } from './S1172/index.js';
import { rule as S1186 } from './S1186/index.js';
import { rule as S1192 } from './S1192/index.js';
import { rule as S1199 } from './S1199/index.js';
import { rule as S1219 } from './S1219/index.js';
import { rule as S1226 } from './S1226/index.js';
import { rule as S1244 } from './S1244/index.js';
import { rule as S1264 } from './S1264/index.js';
import { rule as S1291 } from './S1291/index.js';
import { rule as S1301 } from './S1301/index.js';
import { rule as S1313 } from './S1313/index.js';
import { rule as S1314 } from './S1314/index.js';
import { rule as S1321 } from './S1321/index.js';
import { rule as S1438 } from './S1438/index.js';
import { rule as S1439 } from './S1439/index.js';
import { rule as S1440 } from './S1440/index.js';
import { rule as S1441 } from './S1441/index.js';
import { rule as S1442 } from './S1442/index.js';
import { rule as S1444 } from './S1444/index.js';
import { rule as S1451 } from './S1451/index.js';
import { rule as S1472 } from './S1472/index.js';
import { rule as S1479 } from './S1479/index.js';
import { rule as S1481 } from './S1481/index.js';
import { rule as S1488 } from './S1488/index.js';
import { rule as S1515 } from './S1515/index.js';
import { rule as S1516 } from './S1516/index.js';
import { rule as S1523 } from './S1523/index.js';
import { rule as S1525 } from './S1525/index.js';
import { rule as S1526 } from './S1526/index.js';
import { rule as S1527 } from './S1527/index.js';
import { rule as S1528 } from './S1528/index.js';
import { rule as S1529 } from './S1529/index.js';
import { rule as S1530 } from './S1530/index.js';
import { rule as S1533 } from './S1533/index.js';
import { rule as S1534 } from './S1534/index.js';
import { rule as S1535 } from './S1535/index.js';
import { rule as S1536 } from './S1536/index.js';
import { rule as S1537 } from './S1537/index.js';
import { rule as S1539 } from './S1539/index.js';
import { rule as S1541 } from './S1541/index.js';
import { rule as S1607 } from './S1607/index.js';
import { rule as S1656 } from './S1656/index.js';
import { rule as S1751 } from './S1751/index.js';
import { rule as S1763 } from './S1763/index.js';
import { rule as S1764 } from './S1764/index.js';
import { rule as S1774 } from './S1774/index.js';
import { rule as S1788 } from './S1788/index.js';
import { rule as S1821 } from './S1821/index.js';
import { rule as S1848 } from './S1848/index.js';
import { rule as S1854 } from './S1854/index.js';
import { rule as S1862 } from './S1862/index.js';
import { rule as S1871 } from './S1871/index.js';
import { rule as S1874 } from './S1874/index.js';
import { rule as S1940 } from './S1940/index.js';
import { rule as S1994 } from './S1994/index.js';
import { rule as S2004 } from './S2004/index.js';
import { rule as S2068 } from './S2068/index.js';
import { rule as S2077 } from './S2077/index.js';
import { rule as S2092 } from './S2092/index.js';
import { rule as S2094 } from './S2094/index.js';
import { rule as S2123 } from './S2123/index.js';
import { rule as S2137 } from './S2137/index.js';
import { rule as S2138 } from './S2138/index.js';
import { rule as S2187 } from './S2187/index.js';
import { rule as S2189 } from './S2189/index.js';
import { rule as S2201 } from './S2201/index.js';
import { rule as S2208 } from './S2208/index.js';
import { rule as S2234 } from './S2234/index.js';
import { rule as S2245 } from './S2245/index.js';
import { rule as S2251 } from './S2251/index.js';
import { rule as S2259 } from './S2259/index.js';
import { rule as S2301 } from './S2301/index.js';
import { rule as S2310 } from './S2310/index.js';
import { rule as S2376 } from './S2376/index.js';
import { rule as S2392 } from './S2392/index.js';
import { rule as S2424 } from './S2424/index.js';
import { rule as S2427 } from './S2427/index.js';
import { rule as S2428 } from './S2428/index.js';
import { rule as S2430 } from './S2430/index.js';
import { rule as S2432 } from './S2432/index.js';
import { rule as S2486 } from './S2486/index.js';
import { rule as S2589 } from './S2589/index.js';
import { rule as S2598 } from './S2598/index.js';
import { rule as S2612 } from './S2612/index.js';
import { rule as S2639 } from './S2639/index.js';
import { rule as S2681 } from './S2681/index.js';
import { rule as S2685 } from './S2685/index.js';
import { rule as S2688 } from './S2688/index.js';
import { rule as S2692 } from './S2692/index.js';
import { rule as S2699 } from './S2699/index.js';
import { rule as S2703 } from './S2703/index.js';
import { rule as S2737 } from './S2737/index.js';
import { rule as S2755 } from './S2755/index.js';
import { rule as S2757 } from './S2757/index.js';
import { rule as S2814 } from './S2814/index.js';
import { rule as S2817 } from './S2817/index.js';
import { rule as S2819 } from './S2819/index.js';
import { rule as S2870 } from './S2870/index.js';
import { rule as S2871 } from './S2871/index.js';
import { rule as S2925 } from './S2925/index.js';
import { rule as S2933 } from './S2933/index.js';
import { rule as S2966 } from './S2966/index.js';
import { rule as S2970 } from './S2970/index.js';
import { rule as S2990 } from './S2990/index.js';
import { rule as S2999 } from './S2999/index.js';
import { rule as S3001 } from './S3001/index.js';
import { rule as S3003 } from './S3003/index.js';
import { rule as S3257 } from './S3257/index.js';
import { rule as S3317 } from './S3317/index.js';
import { rule as S3330 } from './S3330/index.js';
import { rule as S3353 } from './S3353/index.js';
import { rule as S3358 } from './S3358/index.js';
import { rule as S3402 } from './S3402/index.js';
import { rule as S3403 } from './S3403/index.js';
import { rule as S3415 } from './S3415/index.js';
import { rule as S3498 } from './S3498/index.js';
import { rule as S3499 } from './S3499/index.js';
import { rule as S3500 } from './S3500/index.js';
import { rule as S3504 } from './S3504/index.js';
import { rule as S3512 } from './S3512/index.js';
import { rule as S3513 } from './S3513/index.js';
import { rule as S3514 } from './S3514/index.js';
import { rule as S3516 } from './S3516/index.js';
import { rule as S3523 } from './S3523/index.js';
import { rule as S3524 } from './S3524/index.js';
import { rule as S3525 } from './S3525/index.js';
import { rule as S3531 } from './S3531/index.js';
import { rule as S3533 } from './S3533/index.js';
import { rule as S3579 } from './S3579/index.js';
import { rule as S3616 } from './S3616/index.js';
import { rule as S3626 } from './S3626/index.js';
import { rule as S3686 } from './S3686/index.js';
import { rule as S3696 } from './S3696/index.js';
import { rule as S3699 } from './S3699/index.js';
import { rule as S3723 } from './S3723/index.js';
import { rule as S3735 } from './S3735/index.js';
import { rule as S3757 } from './S3757/index.js';
import { rule as S3758 } from './S3758/index.js';
import { rule as S3760 } from './S3760/index.js';
import { rule as S3776 } from './S3776/index.js';
import { rule as S3782 } from './S3782/index.js';
import { rule as S3785 } from './S3785/index.js';
import { rule as S3786 } from './S3786/index.js';
import { rule as S3796 } from './S3796/index.js';
import { rule as S3798 } from './S3798/index.js';
import { rule as S3799 } from './S3799/index.js';
import { rule as S3800 } from './S3800/index.js';
import { rule as S3801 } from './S3801/index.js';
import { rule as S3812 } from './S3812/index.js';
import { rule as S3827 } from './S3827/index.js';
import { rule as S3834 } from './S3834/index.js';
import { rule as S3854 } from './S3854/index.js';
import { rule as S3863 } from './S3863/index.js';
import { rule as S3923 } from './S3923/index.js';
import { rule as S3972 } from './S3972/index.js';
import { rule as S3973 } from './S3973/index.js';
import { rule as S3981 } from './S3981/index.js';
import { rule as S3984 } from './S3984/index.js';
import { rule as S4023 } from './S4023/index.js';
import { rule as S4030 } from './S4030/index.js';
import { rule as S4036 } from './S4036/index.js';
import { rule as S4043 } from './S4043/index.js';
import { rule as S4084 } from './S4084/index.js';
import { rule as S4123 } from './S4123/index.js';
import { rule as S4124 } from './S4124/index.js';
import { rule as S4125 } from './S4125/index.js';
import { rule as S4136 } from './S4136/index.js';
import { rule as S4137 } from './S4137/index.js';
import { rule as S4138 } from './S4138/index.js';
import { rule as S4139 } from './S4139/index.js';
import { rule as S4140 } from './S4140/index.js';
import { rule as S4143 } from './S4143/index.js';
import { rule as S4144 } from './S4144/index.js';
import { rule as S4156 } from './S4156/index.js';
import { rule as S4157 } from './S4157/index.js';
import { rule as S4158 } from './S4158/index.js';
import { rule as S4165 } from './S4165/index.js';
import { rule as S4204 } from './S4204/index.js';
import { rule as S4275 } from './S4275/index.js';
import { rule as S4322 } from './S4322/index.js';
import { rule as S4323 } from './S4323/index.js';
import { rule as S4324 } from './S4324/index.js';
import { rule as S4325 } from './S4325/index.js';
import { rule as S4326 } from './S4326/index.js';
import { rule as S4327 } from './S4327/index.js';
import { rule as S4328 } from './S4328/index.js';
import { rule as S4335 } from './S4335/index.js';
import { rule as S4423 } from './S4423/index.js';
import { rule as S4426 } from './S4426/index.js';
import { rule as S4502 } from './S4502/index.js';
import { rule as S4507 } from './S4507/index.js';
import { rule as S4524 } from './S4524/index.js';
import { rule as S4619 } from './S4619/index.js';
import { rule as S4621 } from './S4621/index.js';
import { rule as S4622 } from './S4622/index.js';
import { rule as S4623 } from './S4623/index.js';
import { rule as S4624 } from './S4624/index.js';
import { rule as S4634 } from './S4634/index.js';
import { rule as S4721 } from './S4721/index.js';
import { rule as S4782 } from './S4782/index.js';
import { rule as S4790 } from './S4790/index.js';
import { rule as S4798 } from './S4798/index.js';
import { rule as S4822 } from './S4822/index.js';
import { rule as S4830 } from './S4830/index.js';
import { rule as S5042 } from './S5042/index.js';
import { rule as S5122 } from './S5122/index.js';
import { rule as S5148 } from './S5148/index.js';
import { rule as S5247 } from './S5247/index.js';
import { rule as S5254 } from './S5254/index.js';
import { rule as S5256 } from './S5256/index.js';
import { rule as S5257 } from './S5257/index.js';
import { rule as S5260 } from './S5260/index.js';
import { rule as S5264 } from './S5264/index.js';
import { rule as S5332 } from './S5332/index.js';
import { rule as S5443 } from './S5443/index.js';
import { rule as S5527 } from './S5527/index.js';
import { rule as S5542 } from './S5542/index.js';
import { rule as S5547 } from './S5547/index.js';
import { rule as S5604 } from './S5604/index.js';
import { rule as S5659 } from './S5659/index.js';
import { rule as S5689 } from './S5689/index.js';
import { rule as S5691 } from './S5691/index.js';
import { rule as S5693 } from './S5693/index.js';
import { rule as S5725 } from './S5725/index.js';
import { rule as S5728 } from './S5728/index.js';
import { rule as S5730 } from './S5730/index.js';
import { rule as S5732 } from './S5732/index.js';
import { rule as S5734 } from './S5734/index.js';
import { rule as S5736 } from './S5736/index.js';
import { rule as S5739 } from './S5739/index.js';
import { rule as S5757 } from './S5757/index.js';
import { rule as S5759 } from './S5759/index.js';
import { rule as S5842 } from './S5842/index.js';
import { rule as S5843 } from './S5843/index.js';
import { rule as S5845 } from './S5845/index.js';
import { rule as S5850 } from './S5850/index.js';
import { rule as S5852 } from './S5852/index.js';
import { rule as S5856 } from './S5856/index.js';
import { rule as S5860 } from './S5860/index.js';
import { rule as S5863 } from './S5863/index.js';
import { rule as S5867 } from './S5867/index.js';
import { rule as S5868 } from './S5868/index.js';
import { rule as S5869 } from './S5869/index.js';
import { rule as S5876 } from './S5876/index.js';
import { rule as S5906 } from './S5906/index.js';
import { rule as S5914 } from './S5914/index.js';
import { rule as S5958 } from './S5958/index.js';
import { rule as S5973 } from './S5973/index.js';
import { rule as S5976 } from './S5976/index.js';
import { rule as S6019 } from './S6019/index.js';
import { rule as S6035 } from './S6035/index.js';
import { rule as S6079 } from './S6079/index.js';
import { rule as S6080 } from './S6080/index.js';
import { rule as S6092 } from './S6092/index.js';
import { rule as S6249 } from './S6249/index.js';
import { rule as S6252 } from './S6252/index.js';
import { rule as S6265 } from './S6265/index.js';
import { rule as S6268 } from './S6268/index.js';
import { rule as S6270 } from './S6270/index.js';
import { rule as S6275 } from './S6275/index.js';
import { rule as S6281 } from './S6281/index.js';
import { rule as S6302 } from './S6302/index.js';
import { rule as S6303 } from './S6303/index.js';
import { rule as S6304 } from './S6304/index.js';
import { rule as S6308 } from './S6308/index.js';
import { rule as S6317 } from './S6317/index.js';
import { rule as S6319 } from './S6319/index.js';
import { rule as S6321 } from './S6321/index.js';
import { rule as S6323 } from './S6323/index.js';
import { rule as S6324 } from './S6324/index.js';
import { rule as S6325 } from './S6325/index.js';
import { rule as S6326 } from './S6326/index.js';
import { rule as S6327 } from './S6327/index.js';
import { rule as S6328 } from './S6328/index.js';
import { rule as S6329 } from './S6329/index.js';
import { rule as S6330 } from './S6330/index.js';
import { rule as S6331 } from './S6331/index.js';
import { rule as S6332 } from './S6332/index.js';
import { rule as S6333 } from './S6333/index.js';
import { rule as S6351 } from './S6351/index.js';
import { rule as S6353 } from './S6353/index.js';
import { rule as S6397 } from './S6397/index.js';
import { rule as S6418 } from './S6418/index.js';
import { rule as S6426 } from './S6426/index.js';
import { rule as S6435 } from './S6435/index.js';
import { rule as S6437 } from './S6437/index.js';
import { rule as S6438 } from './S6438/index.js';
import { rule as S6439 } from './S6439/index.js';
import { rule as S6440 } from './S6440/index.js';
import { rule as S6441 } from './S6441/index.js';
import { rule as S6442 } from './S6442/index.js';
import { rule as S6443 } from './S6443/index.js';
import { rule as S6477 } from './S6477/index.js';
import { rule as S6478 } from './S6478/index.js';
import { rule as S6479 } from './S6479/index.js';
import { rule as S6480 } from './S6480/index.js';
import { rule as S6481 } from './S6481/index.js';
import { rule as S6486 } from './S6486/index.js';
import { rule as S6509 } from './S6509/index.js';
import { rule as S6522 } from './S6522/index.js';
import { rule as S6523 } from './S6523/index.js';
import { rule as S6534 } from './S6534/index.js';
import { rule as S6535 } from './S6535/index.js';
import { rule as S6544 } from './S6544/index.js';
import { rule as S6550 } from './S6550/index.js';
import { rule as S6551 } from './S6551/index.js';
import { rule as S6557 } from './S6557/index.js';
import { rule as S6564 } from './S6564/index.js';
import { rule as S6565 } from './S6565/index.js';
import { rule as S6568 } from './S6568/index.js';
import { rule as S6569 } from './S6569/index.js';
import { rule as S6571 } from './S6571/index.js';
import { rule as S6572 } from './S6572/index.js';
import { rule as S6578 } from './S6578/index.js';
import { rule as S6582 } from './S6582/index.js';
import { rule as S6583 } from './S6583/index.js';
import { rule as S6590 } from './S6590/index.js';
import { rule as S6594 } from './S6594/index.js';
import { rule as S6598 } from './S6598/index.js';
import { rule as S6606 } from './S6606/index.js';
import { rule as S6627 } from './S6627/index.js';
import { rule as S6635 } from './S6635/index.js';
import { rule as S6637 } from './S6637/index.js';
import { rule as S6638 } from './S6638/index.js';
import { rule as S6643 } from './S6643/index.js';
import { rule as S6644 } from './S6644/index.js';
import { rule as S6645 } from './S6645/index.js';
import { rule as S6647 } from './S6647/index.js';
import { rule as S6650 } from './S6650/index.js';
import { rule as S6653 } from './S6653/index.js';
import { rule as S6654 } from './S6654/index.js';
import { rule as S6657 } from './S6657/index.js';
import { rule as S6660 } from './S6660/index.js';
import { rule as S6661 } from './S6661/index.js';
import { rule as S6666 } from './S6666/index.js';
import { rule as S6671 } from './S6671/index.js';
import { rule as S6676 } from './S6676/index.js';
import { rule as S6679 } from './S6679/index.js';
import { rule as S6746 } from './S6746/index.js';
import { rule as S6747 } from './S6747/index.js';
import { rule as S6748 } from './S6748/index.js';
import { rule as S6749 } from './S6749/index.js';
import { rule as S6750 } from './S6750/index.js';
import { rule as S6754 } from './S6754/index.js';
import { rule as S6756 } from './S6756/index.js';
import { rule as S6757 } from './S6757/index.js';
import { rule as S6759 } from './S6759/index.js';
import { rule as S6761 } from './S6761/index.js';
import { rule as S6763 } from './S6763/index.js';
import { rule as S6766 } from './S6766/index.js';
import { rule as S6767 } from './S6767/index.js';
import { rule as S6770 } from './S6770/index.js';
import { rule as S6772 } from './S6772/index.js';
import { rule as S6774 } from './S6774/index.js';
import { rule as S6775 } from './S6775/index.js';
import { rule as S6788 } from './S6788/index.js';
import { rule as S6789 } from './S6789/index.js';
import { rule as S6790 } from './S6790/index.js';
import { rule as S6791 } from './S6791/index.js';
import { rule as S6793 } from './S6793/index.js';
import { rule as S6807 } from './S6807/index.js';
import { rule as S6811 } from './S6811/index.js';
import { rule as S6819 } from './S6819/index.js';
import { rule as S6821 } from './S6821/index.js';
import { rule as S6822 } from './S6822/index.js';
import { rule as S6823 } from './S6823/index.js';
import { rule as S6824 } from './S6824/index.js';
import { rule as S6825 } from './S6825/index.js';
import { rule as S6827 } from './S6827/index.js';
import { rule as S6836 } from './S6836/index.js';
import { rule as S6840 } from './S6840/index.js';
import { rule as S6841 } from './S6841/index.js';
import { rule as S6842 } from './S6842/index.js';
import { rule as S6843 } from './S6843/index.js';
import { rule as S6844 } from './S6844/index.js';
import { rule as S6845 } from './S6845/index.js';
import { rule as S6846 } from './S6846/index.js';
import { rule as S6847 } from './S6847/index.js';
import { rule as S6848 } from './S6848/index.js';
import { rule as S6850 } from './S6850/index.js';
import { rule as S6851 } from './S6851/index.js';
import { rule as S6852 } from './S6852/index.js';
import { rule as S6853 } from './S6853/index.js';
import { rule as S6859 } from './S6859/index.js';
import { rule as S6861 } from './S6861/index.js';
import { rule as S6957 } from './S6957/index.js';
import { rule as S6958 } from './S6958/index.js';
import { rule as S6959 } from './S6959/index.js';
import { rule as S7059 } from './S7059/index.js';
import { rule as S7060 } from './S7060/index.js';
import { rule as S7639 } from './S7639/index.js';
import { rule as S7641 } from './S7641/index.js';
import { rule as S7647 } from './S7647/index.js';
import { rule as S7648 } from './S7648/index.js';
import { rule as S7649 } from './S7649/index.js';
import { rule as S7650 } from './S7650/index.js';
import { rule as S7651 } from './S7651/index.js';
import { rule as S7652 } from './S7652/index.js';
import { rule as S7653 } from './S7653/index.js';
import { rule as S7654 } from './S7654/index.js';
import { rule as S7655 } from './S7655/index.js';
import { rule as S7656 } from './S7656/index.js';
import { rule as S7718 } from './S7718/index.js';
import { rule as S7719 } from './S7719/index.js';
import { rule as S7720 } from './S7720/index.js';
import { rule as S7721 } from './S7721/index.js';
import { rule as S7722 } from './S7722/index.js';
import { rule as S7723 } from './S7723/index.js';
import { rule as S7724 } from './S7724/index.js';
import { rule as S7725 } from './S7725/index.js';
import { rule as S7726 } from './S7726/index.js';
import { rule as S7727 } from './S7727/index.js';
import { rule as S7728 } from './S7728/index.js';
import { rule as S7729 } from './S7729/index.js';
import { rule as S7730 } from './S7730/index.js';
import { rule as S7731 } from './S7731/index.js';
import { rule as S7732 } from './S7732/index.js';
import { rule as S7733 } from './S7733/index.js';
import { rule as S7734 } from './S7734/index.js';
import { rule as S7735 } from './S7735/index.js';
import { rule as S7736 } from './S7736/index.js';
import { rule as S7737 } from './S7737/index.js';
import { rule as S7738 } from './S7738/index.js';
import { rule as S7739 } from './S7739/index.js';
import { rule as S7740 } from './S7740/index.js';
import { rule as S7741 } from './S7741/index.js';
import { rule as S7742 } from './S7742/index.js';
import { rule as S7743 } from './S7743/index.js';
import { rule as S7744 } from './S7744/index.js';
import { rule as S7745 } from './S7745/index.js';
import { rule as S7746 } from './S7746/index.js';
import { rule as S7747 } from './S7747/index.js';
import { rule as S7748 } from './S7748/index.js';
import { rule as S7749 } from './S7749/index.js';
import { rule as S7750 } from './S7750/index.js';
import { rule as S7751 } from './S7751/index.js';
import { rule as S7752 } from './S7752/index.js';
import { rule as S7753 } from './S7753/index.js';
import { rule as S7754 } from './S7754/index.js';
import { rule as S7755 } from './S7755/index.js';
import { rule as S7756 } from './S7756/index.js';
import { rule as S7757 } from './S7757/index.js';
import { rule as S7758 } from './S7758/index.js';
import { rule as S7759 } from './S7759/index.js';
import { rule as S7760 } from './S7760/index.js';
import { rule as S7761 } from './S7761/index.js';
import { rule as S7762 } from './S7762/index.js';
import { rule as S7763 } from './S7763/index.js';
import { rule as S7764 } from './S7764/index.js';
import { rule as S7765 } from './S7765/index.js';
import { rule as S7766 } from './S7766/index.js';
import { rule as S7767 } from './S7767/index.js';
import { rule as S7768 } from './S7768/index.js';
import { rule as S7769 } from './S7769/index.js';
import { rule as S7770 } from './S7770/index.js';
import { rule as S7771 } from './S7771/index.js';
import { rule as S7772 } from './S7772/index.js';
import { rule as S7773 } from './S7773/index.js';
import { rule as S7774 } from './S7774/index.js';
import { rule as S7775 } from './S7775/index.js';
import { rule as S7776 } from './S7776/index.js';
import { rule as S7777 } from './S7777/index.js';
import { rule as S7778 } from './S7778/index.js';
import { rule as S7780 } from './S7780/index.js';
import { rule as S7781 } from './S7781/index.js';
import { rule as S7783 } from './S7783/index.js';
import { rule as S7784 } from './S7784/index.js';
import { rule as S7785 } from './S7785/index.js';
import { rule as S7786 } from './S7786/index.js';
import { rule as S7787 } from './S7787/index.js';
import { rule as S7790 } from './S7790/index.js';
import { rule as S8441 } from './S8441/index.js';
import { rule as S8479 } from './S8479/index.js';
import { rule as S8754 } from './S8754/index.js';
import { rule as S8780 } from './S8780/index.js';
import { rule as S8781 } from './S8781/index.js';
import { rule as S8782 } from './S8782/index.js';
import { rule as S8783 } from './S8783/index.js';
import { rule as S8784 } from './S8784/index.js';
import { rule as S8785 } from './S8785/index.js';
import { rule as S8786 } from './S8786/index.js';
import { rule as S8907 } from './S8907/index.js';
import { rule as S8927 } from './S8927/index.js';
import { rule as S8932 } from './S8932/index.js';
import { rule as S8950 } from './S8950/index.js';
import { rule as S8951 } from './S8951/index.js';
import { rule as S8957 } from './S8957/index.js';
import { rule as S8959 } from './S8959/index.js';
import { rule as S8960 } from './S8960/index.js';
import { rule as S8961 } from './S8961/index.js';
import { rule as S8962 } from './S8962/index.js';
import { rule as S8967 } from './S8967/index.js';
import { rule as S8968 } from './S8968/index.js';
import { rule as S8980 } from './S8980/index.js';
import { rule as S8981 } from './S8981/index.js';
import { rule as S8982 } from './S8982/index.js';
import { rule as S8984 } from './S8984/index.js';
import { rule as S8985 } from './S8985/index.js';
import { rule as S8987 } from './S8987/index.js';
import { rule as S8988 } from './S8988/index.js';
import { rule as S8990 } from './S8990/index.js';
import { rule as S8998 } from './S8998/index.js';
import { rule as S9011 } from './S9011/index.js';
import { rule as S9012 } from './S9012/index.js';
import { rule as S9019 } from './S9019/index.js';
import { rule as S9020 } from './S9020/index.js';
import { rule as S9025 } from './S9025/index.js';
import { rule as S9026 } from './S9026/index.js';
import { rule as S9027 } from './S9027/index.js';
import { rule as S9072 } from './S9072/index.js';
import { rule as S9073 } from './S9073/index.js';
import { rule as S9078 } from './S9078/index.js';
import { rule as S9107 } from './S9107/index.js';
import { rule as S9114 } from './S9114/index.js';
import { rule as S9128 } from './S9128/index.js';

export const ruleKeys = {
  S100: 'function-name',
  S101: 'class-name',
  S103: 'max-len',
  S104: 'max-lines',
  S105: 'no-tab',
  S106: 'no-console',
  S107: 'max-params',
  S108: 'no-empty',
  S109: 'no-magic-numbers',
  S113: 'eol-last',
  S117: 'variable-name',
  S121: 'curly',
  S122: 'max-statements-per-line',
  S124: 'comment-regex',
  S125: 'no-commented-code',
  S126: 'elseif-without-else',
  S128: 'no-fallthrough',
  S131: 'switch-without-default',
  S134: 'nested-control-flow',
  S135: 'too-many-break-or-continue-in-loop',
  S138: 'max-lines-per-function',
  S139: 'line-comment-position',
  S878: 'no-sequences',
  S881: 'no-nested-incdec',
  S888: 'no-equals-in-for-termination',
  S905: 'no-unused-expressions',
  S909: 'no-continue',
  S930: 'no-extra-arguments',
  S1066: 'no-collapsible-if',
  S1067: 'expression-complexity',
  S1068: 'no-unused-private-class-members',
  S1077: 'alt-text',
  S1082: 'mouse-events-a11y',
  S1090: 'iframe-has-title',
  S1105: 'brace-style',
  S1110: 'no-redundant-parentheses',
  S1116: 'no-extra-semi',
  S1117: 'no-shadow',
  S1119: 'no-labels',
  S1121: 'no-nested-assignment',
  S1125: 'no-redundant-boolean',
  S1126: 'prefer-single-boolean-return',
  S1128: 'unused-import',
  S1131: 'no-trailing-spaces',
  S1134: 'fixme-tag',
  S1135: 'todo-tag',
  S1143: 'no-unsafe-finally',
  S1154: 'useless-string-operation',
  S1172: 'no-unused-function-argument',
  S1186: 'no-empty-function',
  S1192: 'no-duplicate-string',
  S1199: 'no-lone-blocks',
  S1219: 'no-case-label-in-switch',
  S1226: 'no-parameter-reassignment',
  S1244: 'no-floating-point-equality',
  S1264: 'prefer-while',
  S1291: 'no-sonar-comments',
  S1301: 'no-small-switch',
  S1313: 'no-hardcoded-ip',
  S1314: 'no-octal',
  S1321: 'no-with',
  S1438: 'semi',
  S1439: 'label-position',
  S1440: 'eqeqeq',
  S1441: 'quotes',
  S1442: 'no-alert',
  S1444: 'public-static-readonly',
  S1451: 'file-header',
  S1472: 'call-argument-line',
  S1479: 'max-switch-cases',
  S1481: 'no-unused-vars',
  S1488: 'prefer-immediate-return',
  S1515: 'function-inside-loop',
  S1516: 'no-multi-str',
  S1523: 'code-eval',
  S1525: 'no-debugger',
  S1526: 'no-variable-usage-before-declaration',
  S1527: 'future-reserved-words',
  S1528: 'array-constructor',
  S1529: 'bitwise-operators',
  S1530: 'no-function-declaration-in-block',
  S1533: 'no-primitive-wrappers',
  S1534: 'no-dupe-keys-S1534',
  S1535: 'for-in',
  S1536: 'no-dupe-args',
  S1537: 'comma-dangle',
  S1539: 'strict',
  S1541: 'cyclomatic-complexity',
  S1607: 'no-skipped-tests',
  S1656: 'no-self-assign',
  S1751: 'no-unreachable-loop',
  S1763: 'no-unreachable',
  S1764: 'no-identical-expressions',
  S1774: 'no-ternary',
  S1788: 'default-param-last',
  S1821: 'no-nested-switch',
  S1848: 'constructor-for-side-effects',
  S1854: 'no-dead-store',
  S1862: 'no-identical-conditions',
  S1871: 'no-duplicated-branches',
  S1874: 'deprecation',
  S1940: 'no-inverted-boolean-check',
  S1994: 'misplaced-loop-counter',
  S2004: 'no-nested-functions',
  S2068: 'no-hardcoded-passwords',
  S2077: 'sql-queries',
  S2092: 'insecure-cookie',
  S2094: 'no-extraneous-class',
  S2123: 'no-useless-increment',
  S2137: 'no-globals-shadowing',
  S2138: 'no-undefined-assignment',
  S2187: 'no-empty-test-file',
  S2189: 'no-infinite-loop',
  S2201: 'no-ignored-return',
  S2208: 'no-wildcard-import',
  S2234: 'arguments-order',
  S2245: 'pseudo-random',
  S2251: 'for-loop-increment-sign',
  S2259: 'null-dereference',
  S2301: 'no-selector-parameter',
  S2310: 'updated-loop-counter',
  S2376: 'accessor-pairs',
  S2392: 'block-scoped-var',
  S2424: 'no-built-in-override',
  S2427: 'radix',
  S2428: 'prefer-object-literal',
  S2430: 'new-cap',
  S2432: 'no-setter-return',
  S2486: 'no-ignored-exceptions',
  S2589: 'no-gratuitous-expressions',
  S2598: 'file-uploads',
  S2612: 'file-permissions',
  S2639: 'no-empty-character-class',
  S2681: 'no-unenclosed-multiline-block',
  S2685: 'no-caller',
  S2688: 'use-isnan',
  S2692: 'index-of-compare-to-positive-number',
  S2699: 'assertions-in-tests',
  S2703: 'no-implicit-global',
  S2737: 'no-useless-catch',
  S2755: 'xml-parser-xxe',
  S2757: 'non-existent-operator',
  S2814: 'no-redeclare',
  S2817: 'web-sql-database',
  S2819: 'post-message',
  S2870: 'no-array-delete',
  S2871: 'no-alphabetical-sort',
  S2925: 'no-fixed-wait-in-tests',
  S2933: 'prefer-readonly',
  S2966: 'no-non-null-assertion',
  S2970: 'no-incomplete-assertions',
  S2990: 'no-global-this',
  S2999: 'new-operator-misuse',
  S3001: 'no-delete-var',
  S3003: 'strings-comparison',
  S3257: 'no-inferrable-types',
  S3317: 'file-name-differ-from-class',
  S3330: 'cookie-no-httponly',
  S3353: 'prefer-const',
  S3358: 'no-nested-conditional',
  S3402: 'no-incorrect-string-concat',
  S3403: 'different-types-comparison',
  S3415: 'inverted-assertion-arguments',
  S3498: 'object-shorthand',
  S3499: 'shorthand-property-grouping',
  S3500: 'updated-const-var',
  S3504: 'no-var',
  S3512: 'prefer-template',
  S3513: 'arguments-usage',
  S3514: 'destructuring-assignment-syntax',
  S3516: 'no-invariant-returns',
  S3523: 'no-new-func',
  S3524: 'arrow-function-convention',
  S3525: 'class-prototype',
  S3531: 'generator-without-yield',
  S3533: 'no-require-or-define',
  S3579: 'no-associative-arrays',
  S3616: 'comma-or-logical-or-case',
  S3626: 'no-redundant-jump',
  S3686: 'inconsistent-function-call',
  S3696: 'no-throw-literal',
  S3699: 'no-use-of-empty-return-value',
  S3723: 'enforce-trailing-comma',
  S3735: 'void-use',
  S3757: 'operation-returning-nan',
  S3758: 'values-not-convertible-to-numbers',
  S3760: 'non-number-in-arithmetic-expression',
  S3776: 'cognitive-complexity',
  S3782: 'argument-type',
  S3785: 'in-operator-type-error',
  S3786: 'no-template-curly-in-string',
  S3796: 'array-callback-without-return',
  S3798: 'declarations-in-global-scope',
  S3799: 'no-empty-pattern',
  S3800: 'function-return-type',
  S3801: 'no-inconsistent-returns',
  S3812: 'no-unsafe-negation',
  S3827: 'no-reference-error',
  S3834: 'no-new-native-nonconstructor',
  S3854: 'super-invocation',
  S3863: 'no-duplicates',
  S3923: 'no-all-duplicated-branches',
  S3972: 'no-same-line-conditional',
  S3973: 'conditional-indentation',
  S3981: 'no-collection-size-mischeck',
  S3984: 'no-unthrown-error',
  S4023: 'no-empty-interface',
  S4030: 'no-unused-collection',
  S4036: 'no-os-command-from-path',
  S4043: 'no-misleading-array-reverse',
  S4084: 'media-has-caption',
  S4123: 'await-thenable',
  S4124: 'no-misused-new',
  S4125: 'valid-typeof',
  S4136: 'adjacent-overload-signatures',
  S4137: 'consistent-type-assertions',
  S4138: 'prefer-for-of',
  S4139: 'no-for-in-iterable',
  S4140: 'no-sparse-arrays',
  S4143: 'no-element-overwrite',
  S4144: 'no-identical-functions',
  S4156: 'prefer-namespace-keyword',
  S4157: 'no-unnecessary-type-arguments',
  S4158: 'no-empty-collection',
  S4165: 'no-redundant-assignments',
  S4204: 'no-explicit-any',
  S4275: 'no-accessor-field-mismatch',
  S4322: 'prefer-type-guard',
  S4323: 'use-type-alias',
  S4324: 'no-return-type-any',
  S4325: 'no-unnecessary-type-assertion',
  S4326: 'no-return-await',
  S4327: 'no-this-alias',
  S4328: 'no-implicit-dependencies',
  S4335: 'no-useless-intersection',
  S4423: 'weak-ssl',
  S4426: 'no-weak-keys',
  S4502: 'csrf',
  S4507: 'production-debug',
  S4524: 'prefer-default-last',
  S4619: 'no-in-misuse',
  S4621: 'no-duplicate-in-composite',
  S4622: 'max-union-size',
  S4623: 'no-undefined-argument',
  S4624: 'no-nested-template-literals',
  S4634: 'prefer-promise-shorthand',
  S4721: 'os-command',
  S4782: 'no-redundant-optional',
  S4790: 'hashing',
  S4798: 'bool-param-default',
  S4822: 'no-try-promise',
  S4830: 'unverified-certificate',
  S5042: 'no-unsafe-unzip',
  S5122: 'cors',
  S5148: 'link-with-target-blank',
  S5247: 'disabled-auto-escaping',
  S5254: 'html-has-lang',
  S5256: 'table-header',
  S5257: 'no-table-as-layout',
  S5260: 'table-header-reference',
  S5264: 'object-alt-content',
  S5332: 'no-clear-text-protocols',
  S5443: 'publicly-writable-directories',
  S5527: 'unverified-hostname',
  S5542: 'encryption-secure-mode',
  S5547: 'no-weak-cipher',
  S5604: 'no-intrusive-permissions',
  S5659: 'insecure-jwt-token',
  S5689: 'x-powered-by',
  S5691: 'hidden-files',
  S5693: 'content-length',
  S5725: 'disabled-resource-integrity',
  S5728: 'content-security-policy',
  S5730: 'no-mixed-content',
  S5732: 'frame-ancestors',
  S5734: 'no-mime-sniff',
  S5736: 'no-referrer-policy',
  S5739: 'strict-transport-security',
  S5757: 'confidential-information-logging',
  S5759: 'no-ip-forward',
  S5842: 'empty-string-repetition',
  S5843: 'regex-complexity',
  S5845: 'no-incompatible-assertion-types',
  S5850: 'anchor-precedence',
  S5852: 'slow-regex',
  S5856: 'no-invalid-regexp',
  S5860: 'unused-named-groups',
  S5863: 'no-same-argument-assert',
  S5867: 'unicode-aware-regex',
  S5868: 'no-misleading-character-class',
  S5869: 'duplicates-in-character-class',
  S5876: 'session-regeneration',
  S5906: 'prefer-specific-assertions',
  S5914: 'no-trivial-assertions',
  S5958: 'test-check-exception',
  S5973: 'stable-tests',
  S5976: 'parameterized-tests',
  S6019: 'no-empty-after-reluctant',
  S6035: 'single-character-alternation',
  S6079: 'no-code-after-done',
  S6080: 'disabled-timeout',
  S6092: 'chai-determinate-assertion',
  S6249: 'aws-s3-bucket-insecure-http',
  S6252: 'aws-s3-bucket-versioning',
  S6265: 'aws-s3-bucket-granted-access',
  S6268: 'no-angular-bypass-sanitization',
  S6270: 'aws-iam-public-access',
  S6275: 'aws-ec2-unencrypted-ebs-volume',
  S6281: 'aws-s3-bucket-public-access',
  S6302: 'aws-iam-all-privileges',
  S6303: 'aws-rds-unencrypted-databases',
  S6304: 'aws-iam-all-resources-accessible',
  S6308: 'aws-opensearchservice-domain',
  S6317: 'aws-iam-privilege-escalation',
  S6319: 'aws-sagemaker-unencrypted-notebook',
  S6321: 'aws-restricted-ip-admin-access',
  S6323: 'no-empty-alternatives',
  S6324: 'no-control-regex',
  S6325: 'prefer-regex-literals',
  S6326: 'no-regex-spaces',
  S6327: 'aws-sns-unencrypted-topics',
  S6328: 'existing-groups',
  S6329: 'aws-ec2-rds-dms-public',
  S6330: 'aws-sqs-unencrypted-queue',
  S6331: 'no-empty-group',
  S6332: 'aws-efs-unencrypted',
  S6333: 'aws-apigateway-public-api',
  S6351: 'stateful-regex',
  S6353: 'concise-regex',
  S6397: 'single-char-in-character-classes',
  S6418: 'no-hardcoded-secrets',
  S6426: 'no-exclusive-tests',
  S6435: 'require-render-return',
  S6437: 'hardcoded-secret-signatures',
  S6438: 'jsx-no-comment-textnodes',
  S6439: 'jsx-no-leaked-render',
  S6440: 'rules-of-hooks',
  S6441: 'no-unused-class-component-methods',
  S6442: 'no-hook-setter-in-body',
  S6443: 'no-useless-react-setstate',
  S6477: 'jsx-key',
  S6478: 'no-unstable-nested-components',
  S6479: 'no-array-index-key',
  S6480: 'jsx-no-bind',
  S6481: 'jsx-no-constructed-context-values',
  S6486: 'no-uniq-key',
  S6509: 'no-extra-boolean-cast',
  S6522: 'no-import-assign',
  S6523: 'no-unsafe-optional-chaining',
  S6534: 'no-loss-of-precision',
  S6535: 'unnecessary-character-escapes',
  S6544: 'no-misused-promises',
  S6550: 'prefer-literal-enum-member',
  S6551: 'no-base-to-string',
  S6557: 'prefer-string-starts-ends-with',
  S6564: 'redundant-type-aliases',
  S6565: 'prefer-return-this-type',
  S6568: 'no-confusing-non-null-assertion',
  S6569: 'no-unnecessary-type-constraint',
  S6571: 'no-redundant-type-constituents',
  S6572: 'prefer-enum-initializers',
  S6578: 'no-duplicate-enum-values',
  S6582: 'prefer-optional-chain',
  S6583: 'no-mixed-enums',
  S6590: 'prefer-as-const',
  S6594: 'prefer-regexp-exec',
  S6598: 'prefer-function-type',
  S6606: 'prefer-nullish-coalescing',
  S6627: 'no-internal-api-use',
  S6635: 'no-constructor-return',
  S6637: 'no-extra-bind',
  S6638: 'no-constant-binary-expression',
  S6643: 'no-extend-native',
  S6644: 'no-unneeded-ternary',
  S6645: 'no-undef-init',
  S6647: 'no-useless-constructor',
  S6650: 'no-useless-rename',
  S6653: 'prefer-object-has-own',
  S6654: 'no-proto',
  S6657: 'no-octal-escape',
  S6660: 'no-lonely-if',
  S6661: 'prefer-object-spread',
  S6666: 'prefer-spread',
  S6671: 'prefer-promise-reject-errors',
  S6676: 'no-useless-call',
  S6679: 'no-self-compare',
  S6746: 'no-direct-mutation-state',
  S6747: 'no-unknown-property',
  S6748: 'no-children-prop',
  S6749: 'jsx-no-useless-fragment',
  S6750: 'no-render-return-value',
  S6754: 'hook-use-state',
  S6756: 'no-access-state-in-setstate',
  S6757: 'no-this-in-sfc',
  S6759: 'prefer-read-only-props',
  S6761: 'no-danger-with-children',
  S6763: 'no-redundant-should-component-update',
  S6766: 'no-unescaped-entities',
  S6767: 'no-unused-prop-types',
  S6770: 'jsx-pascal-case',
  S6772: 'jsx-child-element-spacing',
  S6774: 'prop-types',
  S6775: 'default-props-match-prop-types',
  S6788: 'no-find-dom-node',
  S6789: 'no-is-mounted',
  S6790: 'no-string-refs',
  S6791: 'no-unsafe',
  S6793: 'aria-proptypes',
  S6807: 'role-has-required-aria-props',
  S6811: 'role-supports-aria-props',
  S6819: 'prefer-tag-over-role',
  S6821: 'aria-role',
  S6822: 'no-redundant-roles',
  S6823: 'aria-activedescendant-has-tabindex',
  S6824: 'aria-unsupported-elements',
  S6825: 'no-aria-hidden-on-focusable',
  S6827: 'anchor-has-content',
  S6836: 'no-case-declarations',
  S6840: 'autocomplete-valid',
  S6841: 'tabindex-no-positive',
  S6842: 'no-noninteractive-element-to-interactive-role',
  S6843: 'no-interactive-element-to-noninteractive-role',
  S6844: 'anchor-is-valid',
  S6845: 'no-noninteractive-tabindex',
  S6846: 'no-access-key',
  S6847: 'no-noninteractive-element-interactions',
  S6848: 'no-static-element-interactions',
  S6850: 'heading-has-content',
  S6851: 'img-redundant-alt',
  S6852: 'interactive-supports-focus',
  S6853: 'label-has-associated-control',
  S6859: 'no-absolute-path',
  S6861: 'no-mutable-exports',
  S6957: 'no-deprecated-react',
  S6958: 'no-literal-call',
  S6959: 'reduce-initial-value',
  S7059: 'no-async-constructor',
  S7060: 'no-self-import',
  S7639: 'review-blockchain-mnemonic',
  S7641: 'contextual-lifecycle',
  S7647: 'no-empty-lifecycle-method',
  S7648: 'prefer-standalone',
  S7649: 'no-input-rename',
  S7650: 'no-inputs-metadata-property',
  S7651: 'no-output-native',
  S7652: 'no-output-on-prefix',
  S7653: 'no-output-rename',
  S7654: 'no-outputs-metadata-property',
  S7655: 'use-lifecycle-interface',
  S7656: 'use-pipe-transform-interface',
  S7718: 'catch-error-name',
  S7719: 'consistent-date-clone',
  S7720: 'consistent-empty-array-spread',
  S7721: 'consistent-function-scoping',
  S7722: 'error-message',
  S7723: 'new-for-builtins',
  S7724: 'no-abusive-eslint-disable',
  S7725: 'no-accessor-recursion',
  S7726: 'no-anonymous-default-export',
  S7727: 'no-array-callback-reference',
  S7728: 'no-array-for-each',
  S7729: 'no-array-method-this-argument',
  S7730: 'no-await-expression-member',
  S7731: 'no-for-loop',
  S7732: 'no-instanceof-builtins',
  S7733: 'no-invalid-fetch-options',
  S7734: 'no-named-default',
  S7735: 'no-negated-condition',
  S7736: 'no-negation-in-equality-check',
  S7737: 'no-object-as-default-parameter',
  S7738: 'no-single-promise-in-promise-methods',
  S7739: 'no-thenable',
  S7740: 'no-this-assignment',
  S7741: 'no-typeof-undefined',
  S7742: 'no-unnecessary-polyfills',
  S7743: 'no-unreadable-iife',
  S7744: 'no-useless-fallback-in-spread',
  S7745: 'no-useless-length-check',
  S7746: 'no-useless-promise-resolve-reject',
  S7747: 'no-useless-spread',
  S7748: 'no-zero-fractions',
  S7749: 'numeric-separators-style',
  S7750: 'prefer-array-find',
  S7751: 'prefer-array-flat',
  S7752: 'prefer-array-flat-map',
  S7753: 'prefer-array-index-of',
  S7754: 'prefer-array-some',
  S7755: 'prefer-at',
  S7756: 'prefer-blob-reading-methods',
  S7757: 'prefer-class-fields',
  S7758: 'prefer-code-point',
  S7759: 'prefer-date-now',
  S7760: 'prefer-default-parameters',
  S7761: 'dom-node-dataset',
  S7762: 'prefer-dom-node-remove',
  S7763: 'prefer-export-from',
  S7764: 'prefer-global-this',
  S7765: 'prefer-includes',
  S7766: 'prefer-math-min-max',
  S7767: 'prefer-math-trunc',
  S7768: 'prefer-modern-dom-apis',
  S7769: 'prefer-modern-math-apis',
  S7770: 'prefer-native-coercion-functions',
  S7771: 'prefer-negative-index',
  S7772: 'prefer-node-protocol',
  S7773: 'prefer-number-properties',
  S7774: 'prefer-prototype-methods',
  S7775: 'prefer-regexp-test',
  S7776: 'prefer-set-has',
  S7777: 'prefer-set-size',
  S7778: 'prefer-single-call',
  S7780: 'prefer-string-raw',
  S7781: 'prefer-string-replace-all',
  S7783: 'prefer-string-trim-start-end',
  S7784: 'prefer-structured-clone',
  S7785: 'prefer-top-level-await',
  S7786: 'prefer-type-error',
  S7787: 'require-module-specifiers',
  S7790: 'dynamically-constructed-templates',
  S8441: 'no-session-cookies-on-static-assets',
  S8479: 'dompurify-unsafe-config',
  S8754: 'no-duplicate-test-title',
  S8780: 'async-test-assertions',
  S8781: 'no-empty-test-title',
  S8782: 'hooks-before-test-cases',
  S8783: 'no-forced-browser-interaction',
  S8784: 'assertions-in-test-cases',
  S8785: 'synchronous-suite-callback',
  S8786: 'super-linear-regex',
  S8907: 'prefer-native-lodash-alternative',
  S8927: 'no-default-utility-imports',
  S8932: 'memoize-cache-key',
  S8950: 'no-required-prop-with-default',
  S8951: 'no-mutating-props',
  S8957: 'require-prop-types',
  S8959: 'no-debug-commands-in-ui-tests',
  S8960: 'no-mixed-completion-style',
  S8961: 'require-explicit-emits',
  S8962: 'require-typed-ref',
  S8967: 'no-interpolation-in-inline-snapshots',
  S8968: 'explicit-test-skip',
  S8980: 'no-unnecessary-act',
  S8981: 'no-global-regexp-flag-in-query',
  S8982: 'require-v-for-key',
  S8984: 'valid-v-for',
  S8985: 'no-wait-for-side-effects',
  S8987: 'no-use-v-if-with-v-for',
  S8988: 'no-side-effects-in-computed-properties',
  S8990: 'no-promise-in-fire-event',
  S8998: 'no-empty-parameterized-test-dataset',
  S9011: 'button-has-type',
  S9012: 'no-wait-for-snapshot',
  S9019: 'no-ref-as-operand',
  S9020: 'prefer-find-by',
  S9025: 'no-async-in-computed-properties',
  S9026: 'await-async-queries',
  S9027: 'testing-library-query-assertion',
  S9072: 'synchronous-exception-assertions',
  S9073: 'composite-assertions',
  S9078: 'no-duplicate-parameterized-test-case',
  S9107: 'require-prop-type-constructor',
  S9114: 'no-debounce-throttle-in-render',
  S9128: 'no-dupe-keys-S9128',
} as const;

export const rules = {
  'function-name': S100,
  'class-name': S101,
  'max-len': S103,
  'max-lines': S104,
  'no-tab': S105,
  'no-console': S106,
  'max-params': S107,
  'no-empty': S108,
  'no-magic-numbers': S109,
  'eol-last': S113,
  'variable-name': S117,
  curly: S121,
  'max-statements-per-line': S122,
  'comment-regex': S124,
  'no-commented-code': S125,
  'elseif-without-else': S126,
  'no-fallthrough': S128,
  'switch-without-default': S131,
  'nested-control-flow': S134,
  'too-many-break-or-continue-in-loop': S135,
  'max-lines-per-function': S138,
  'line-comment-position': S139,
  'no-sequences': S878,
  'no-nested-incdec': S881,
  'no-equals-in-for-termination': S888,
  'no-unused-expressions': S905,
  'no-continue': S909,
  'no-extra-arguments': S930,
  'no-collapsible-if': S1066,
  'expression-complexity': S1067,
  'no-unused-private-class-members': S1068,
  'alt-text': S1077,
  'mouse-events-a11y': S1082,
  'iframe-has-title': S1090,
  'brace-style': S1105,
  'no-redundant-parentheses': S1110,
  'no-extra-semi': S1116,
  'no-shadow': S1117,
  'no-labels': S1119,
  'no-nested-assignment': S1121,
  'no-redundant-boolean': S1125,
  'prefer-single-boolean-return': S1126,
  'unused-import': S1128,
  'no-trailing-spaces': S1131,
  'fixme-tag': S1134,
  'todo-tag': S1135,
  'no-unsafe-finally': S1143,
  'useless-string-operation': S1154,
  'no-unused-function-argument': S1172,
  'no-empty-function': S1186,
  'no-duplicate-string': S1192,
  'no-lone-blocks': S1199,
  'no-case-label-in-switch': S1219,
  'no-parameter-reassignment': S1226,
  'no-floating-point-equality': S1244,
  'prefer-while': S1264,
  'no-sonar-comments': S1291,
  'no-small-switch': S1301,
  'no-hardcoded-ip': S1313,
  'no-octal': S1314,
  'no-with': S1321,
  semi: S1438,
  'label-position': S1439,
  eqeqeq: S1440,
  quotes: S1441,
  'no-alert': S1442,
  'public-static-readonly': S1444,
  'file-header': S1451,
  'call-argument-line': S1472,
  'max-switch-cases': S1479,
  'no-unused-vars': S1481,
  'prefer-immediate-return': S1488,
  'function-inside-loop': S1515,
  'no-multi-str': S1516,
  'code-eval': S1523,
  'no-debugger': S1525,
  'no-variable-usage-before-declaration': S1526,
  'future-reserved-words': S1527,
  'array-constructor': S1528,
  'bitwise-operators': S1529,
  'no-function-declaration-in-block': S1530,
  'no-primitive-wrappers': S1533,
  'no-dupe-keys-S1534': S1534,
  'for-in': S1535,
  'no-dupe-args': S1536,
  'comma-dangle': S1537,
  strict: S1539,
  'cyclomatic-complexity': S1541,
  'no-skipped-tests': S1607,
  'no-self-assign': S1656,
  'no-unreachable-loop': S1751,
  'no-unreachable': S1763,
  'no-identical-expressions': S1764,
  'no-ternary': S1774,
  'default-param-last': S1788,
  'no-nested-switch': S1821,
  'constructor-for-side-effects': S1848,
  'no-dead-store': S1854,
  'no-identical-conditions': S1862,
  'no-duplicated-branches': S1871,
  deprecation: S1874,
  'no-inverted-boolean-check': S1940,
  'misplaced-loop-counter': S1994,
  'no-nested-functions': S2004,
  'no-hardcoded-passwords': S2068,
  'sql-queries': S2077,
  'insecure-cookie': S2092,
  'no-extraneous-class': S2094,
  'no-useless-increment': S2123,
  'no-globals-shadowing': S2137,
  'no-undefined-assignment': S2138,
  'no-empty-test-file': S2187,
  'no-infinite-loop': S2189,
  'no-ignored-return': S2201,
  'no-wildcard-import': S2208,
  'arguments-order': S2234,
  'pseudo-random': S2245,
  'for-loop-increment-sign': S2251,
  'null-dereference': S2259,
  'no-selector-parameter': S2301,
  'updated-loop-counter': S2310,
  'accessor-pairs': S2376,
  'block-scoped-var': S2392,
  'no-built-in-override': S2424,
  radix: S2427,
  'prefer-object-literal': S2428,
  'new-cap': S2430,
  'no-setter-return': S2432,
  'no-ignored-exceptions': S2486,
  'no-gratuitous-expressions': S2589,
  'file-uploads': S2598,
  'file-permissions': S2612,
  'no-empty-character-class': S2639,
  'no-unenclosed-multiline-block': S2681,
  'no-caller': S2685,
  'use-isnan': S2688,
  'index-of-compare-to-positive-number': S2692,
  'assertions-in-tests': S2699,
  'no-implicit-global': S2703,
  'no-useless-catch': S2737,
  'xml-parser-xxe': S2755,
  'non-existent-operator': S2757,
  'no-redeclare': S2814,
  'web-sql-database': S2817,
  'post-message': S2819,
  'no-array-delete': S2870,
  'no-alphabetical-sort': S2871,
  'no-fixed-wait-in-tests': S2925,
  'prefer-readonly': S2933,
  'no-non-null-assertion': S2966,
  'no-incomplete-assertions': S2970,
  'no-global-this': S2990,
  'new-operator-misuse': S2999,
  'no-delete-var': S3001,
  'strings-comparison': S3003,
  'no-inferrable-types': S3257,
  'file-name-differ-from-class': S3317,
  'cookie-no-httponly': S3330,
  'prefer-const': S3353,
  'no-nested-conditional': S3358,
  'no-incorrect-string-concat': S3402,
  'different-types-comparison': S3403,
  'inverted-assertion-arguments': S3415,
  'object-shorthand': S3498,
  'shorthand-property-grouping': S3499,
  'updated-const-var': S3500,
  'no-var': S3504,
  'prefer-template': S3512,
  'arguments-usage': S3513,
  'destructuring-assignment-syntax': S3514,
  'no-invariant-returns': S3516,
  'no-new-func': S3523,
  'arrow-function-convention': S3524,
  'class-prototype': S3525,
  'generator-without-yield': S3531,
  'no-require-or-define': S3533,
  'no-associative-arrays': S3579,
  'comma-or-logical-or-case': S3616,
  'no-redundant-jump': S3626,
  'inconsistent-function-call': S3686,
  'no-throw-literal': S3696,
  'no-use-of-empty-return-value': S3699,
  'enforce-trailing-comma': S3723,
  'void-use': S3735,
  'operation-returning-nan': S3757,
  'values-not-convertible-to-numbers': S3758,
  'non-number-in-arithmetic-expression': S3760,
  'cognitive-complexity': S3776,
  'argument-type': S3782,
  'in-operator-type-error': S3785,
  'no-template-curly-in-string': S3786,
  'array-callback-without-return': S3796,
  'declarations-in-global-scope': S3798,
  'no-empty-pattern': S3799,
  'function-return-type': S3800,
  'no-inconsistent-returns': S3801,
  'no-unsafe-negation': S3812,
  'no-reference-error': S3827,
  'no-new-native-nonconstructor': S3834,
  'super-invocation': S3854,
  'no-duplicates': S3863,
  'no-all-duplicated-branches': S3923,
  'no-same-line-conditional': S3972,
  'conditional-indentation': S3973,
  'no-collection-size-mischeck': S3981,
  'no-unthrown-error': S3984,
  'no-empty-interface': S4023,
  'no-unused-collection': S4030,
  'no-os-command-from-path': S4036,
  'no-misleading-array-reverse': S4043,
  'media-has-caption': S4084,
  'await-thenable': S4123,
  'no-misused-new': S4124,
  'valid-typeof': S4125,
  'adjacent-overload-signatures': S4136,
  'consistent-type-assertions': S4137,
  'prefer-for-of': S4138,
  'no-for-in-iterable': S4139,
  'no-sparse-arrays': S4140,
  'no-element-overwrite': S4143,
  'no-identical-functions': S4144,
  'prefer-namespace-keyword': S4156,
  'no-unnecessary-type-arguments': S4157,
  'no-empty-collection': S4158,
  'no-redundant-assignments': S4165,
  'no-explicit-any': S4204,
  'no-accessor-field-mismatch': S4275,
  'prefer-type-guard': S4322,
  'use-type-alias': S4323,
  'no-return-type-any': S4324,
  'no-unnecessary-type-assertion': S4325,
  'no-return-await': S4326,
  'no-this-alias': S4327,
  'no-implicit-dependencies': S4328,
  'no-useless-intersection': S4335,
  'weak-ssl': S4423,
  'no-weak-keys': S4426,
  csrf: S4502,
  'production-debug': S4507,
  'prefer-default-last': S4524,
  'no-in-misuse': S4619,
  'no-duplicate-in-composite': S4621,
  'max-union-size': S4622,
  'no-undefined-argument': S4623,
  'no-nested-template-literals': S4624,
  'prefer-promise-shorthand': S4634,
  'os-command': S4721,
  'no-redundant-optional': S4782,
  hashing: S4790,
  'bool-param-default': S4798,
  'no-try-promise': S4822,
  'unverified-certificate': S4830,
  'no-unsafe-unzip': S5042,
  cors: S5122,
  'link-with-target-blank': S5148,
  'disabled-auto-escaping': S5247,
  'html-has-lang': S5254,
  'table-header': S5256,
  'no-table-as-layout': S5257,
  'table-header-reference': S5260,
  'object-alt-content': S5264,
  'no-clear-text-protocols': S5332,
  'publicly-writable-directories': S5443,
  'unverified-hostname': S5527,
  'encryption-secure-mode': S5542,
  'no-weak-cipher': S5547,
  'no-intrusive-permissions': S5604,
  'insecure-jwt-token': S5659,
  'x-powered-by': S5689,
  'hidden-files': S5691,
  'content-length': S5693,
  'disabled-resource-integrity': S5725,
  'content-security-policy': S5728,
  'no-mixed-content': S5730,
  'frame-ancestors': S5732,
  'no-mime-sniff': S5734,
  'no-referrer-policy': S5736,
  'strict-transport-security': S5739,
  'confidential-information-logging': S5757,
  'no-ip-forward': S5759,
  'empty-string-repetition': S5842,
  'regex-complexity': S5843,
  'no-incompatible-assertion-types': S5845,
  'anchor-precedence': S5850,
  'slow-regex': S5852,
  'no-invalid-regexp': S5856,
  'unused-named-groups': S5860,
  'no-same-argument-assert': S5863,
  'unicode-aware-regex': S5867,
  'no-misleading-character-class': S5868,
  'duplicates-in-character-class': S5869,
  'session-regeneration': S5876,
  'prefer-specific-assertions': S5906,
  'no-trivial-assertions': S5914,
  'test-check-exception': S5958,
  'stable-tests': S5973,
  'parameterized-tests': S5976,
  'no-empty-after-reluctant': S6019,
  'single-character-alternation': S6035,
  'no-code-after-done': S6079,
  'disabled-timeout': S6080,
  'chai-determinate-assertion': S6092,
  'aws-s3-bucket-insecure-http': S6249,
  'aws-s3-bucket-versioning': S6252,
  'aws-s3-bucket-granted-access': S6265,
  'no-angular-bypass-sanitization': S6268,
  'aws-iam-public-access': S6270,
  'aws-ec2-unencrypted-ebs-volume': S6275,
  'aws-s3-bucket-public-access': S6281,
  'aws-iam-all-privileges': S6302,
  'aws-rds-unencrypted-databases': S6303,
  'aws-iam-all-resources-accessible': S6304,
  'aws-opensearchservice-domain': S6308,
  'aws-iam-privilege-escalation': S6317,
  'aws-sagemaker-unencrypted-notebook': S6319,
  'aws-restricted-ip-admin-access': S6321,
  'no-empty-alternatives': S6323,
  'no-control-regex': S6324,
  'prefer-regex-literals': S6325,
  'no-regex-spaces': S6326,
  'aws-sns-unencrypted-topics': S6327,
  'existing-groups': S6328,
  'aws-ec2-rds-dms-public': S6329,
  'aws-sqs-unencrypted-queue': S6330,
  'no-empty-group': S6331,
  'aws-efs-unencrypted': S6332,
  'aws-apigateway-public-api': S6333,
  'stateful-regex': S6351,
  'concise-regex': S6353,
  'single-char-in-character-classes': S6397,
  'no-hardcoded-secrets': S6418,
  'no-exclusive-tests': S6426,
  'require-render-return': S6435,
  'hardcoded-secret-signatures': S6437,
  'jsx-no-comment-textnodes': S6438,
  'jsx-no-leaked-render': S6439,
  'rules-of-hooks': S6440,
  'no-unused-class-component-methods': S6441,
  'no-hook-setter-in-body': S6442,
  'no-useless-react-setstate': S6443,
  'jsx-key': S6477,
  'no-unstable-nested-components': S6478,
  'no-array-index-key': S6479,
  'jsx-no-bind': S6480,
  'jsx-no-constructed-context-values': S6481,
  'no-uniq-key': S6486,
  'no-extra-boolean-cast': S6509,
  'no-import-assign': S6522,
  'no-unsafe-optional-chaining': S6523,
  'no-loss-of-precision': S6534,
  'unnecessary-character-escapes': S6535,
  'no-misused-promises': S6544,
  'prefer-literal-enum-member': S6550,
  'no-base-to-string': S6551,
  'prefer-string-starts-ends-with': S6557,
  'redundant-type-aliases': S6564,
  'prefer-return-this-type': S6565,
  'no-confusing-non-null-assertion': S6568,
  'no-unnecessary-type-constraint': S6569,
  'no-redundant-type-constituents': S6571,
  'prefer-enum-initializers': S6572,
  'no-duplicate-enum-values': S6578,
  'prefer-optional-chain': S6582,
  'no-mixed-enums': S6583,
  'prefer-as-const': S6590,
  'prefer-regexp-exec': S6594,
  'prefer-function-type': S6598,
  'prefer-nullish-coalescing': S6606,
  'no-internal-api-use': S6627,
  'no-constructor-return': S6635,
  'no-extra-bind': S6637,
  'no-constant-binary-expression': S6638,
  'no-extend-native': S6643,
  'no-unneeded-ternary': S6644,
  'no-undef-init': S6645,
  'no-useless-constructor': S6647,
  'no-useless-rename': S6650,
  'prefer-object-has-own': S6653,
  'no-proto': S6654,
  'no-octal-escape': S6657,
  'no-lonely-if': S6660,
  'prefer-object-spread': S6661,
  'prefer-spread': S6666,
  'prefer-promise-reject-errors': S6671,
  'no-useless-call': S6676,
  'no-self-compare': S6679,
  'no-direct-mutation-state': S6746,
  'no-unknown-property': S6747,
  'no-children-prop': S6748,
  'jsx-no-useless-fragment': S6749,
  'no-render-return-value': S6750,
  'hook-use-state': S6754,
  'no-access-state-in-setstate': S6756,
  'no-this-in-sfc': S6757,
  'prefer-read-only-props': S6759,
  'no-danger-with-children': S6761,
  'no-redundant-should-component-update': S6763,
  'no-unescaped-entities': S6766,
  'no-unused-prop-types': S6767,
  'jsx-pascal-case': S6770,
  'jsx-child-element-spacing': S6772,
  'prop-types': S6774,
  'default-props-match-prop-types': S6775,
  'no-find-dom-node': S6788,
  'no-is-mounted': S6789,
  'no-string-refs': S6790,
  'no-unsafe': S6791,
  'aria-proptypes': S6793,
  'role-has-required-aria-props': S6807,
  'role-supports-aria-props': S6811,
  'prefer-tag-over-role': S6819,
  'aria-role': S6821,
  'no-redundant-roles': S6822,
  'aria-activedescendant-has-tabindex': S6823,
  'aria-unsupported-elements': S6824,
  'no-aria-hidden-on-focusable': S6825,
  'anchor-has-content': S6827,
  'no-case-declarations': S6836,
  'autocomplete-valid': S6840,
  'tabindex-no-positive': S6841,
  'no-noninteractive-element-to-interactive-role': S6842,
  'no-interactive-element-to-noninteractive-role': S6843,
  'anchor-is-valid': S6844,
  'no-noninteractive-tabindex': S6845,
  'no-access-key': S6846,
  'no-noninteractive-element-interactions': S6847,
  'no-static-element-interactions': S6848,
  'heading-has-content': S6850,
  'img-redundant-alt': S6851,
  'interactive-supports-focus': S6852,
  'label-has-associated-control': S6853,
  'no-absolute-path': S6859,
  'no-mutable-exports': S6861,
  'no-deprecated-react': S6957,
  'no-literal-call': S6958,
  'reduce-initial-value': S6959,
  'no-async-constructor': S7059,
  'no-self-import': S7060,
  'review-blockchain-mnemonic': S7639,
  'contextual-lifecycle': S7641,
  'no-empty-lifecycle-method': S7647,
  'prefer-standalone': S7648,
  'no-input-rename': S7649,
  'no-inputs-metadata-property': S7650,
  'no-output-native': S7651,
  'no-output-on-prefix': S7652,
  'no-output-rename': S7653,
  'no-outputs-metadata-property': S7654,
  'use-lifecycle-interface': S7655,
  'use-pipe-transform-interface': S7656,
  'catch-error-name': S7718,
  'consistent-date-clone': S7719,
  'consistent-empty-array-spread': S7720,
  'consistent-function-scoping': S7721,
  'error-message': S7722,
  'new-for-builtins': S7723,
  'no-abusive-eslint-disable': S7724,
  'no-accessor-recursion': S7725,
  'no-anonymous-default-export': S7726,
  'no-array-callback-reference': S7727,
  'no-array-for-each': S7728,
  'no-array-method-this-argument': S7729,
  'no-await-expression-member': S7730,
  'no-for-loop': S7731,
  'no-instanceof-builtins': S7732,
  'no-invalid-fetch-options': S7733,
  'no-named-default': S7734,
  'no-negated-condition': S7735,
  'no-negation-in-equality-check': S7736,
  'no-object-as-default-parameter': S7737,
  'no-single-promise-in-promise-methods': S7738,
  'no-thenable': S7739,
  'no-this-assignment': S7740,
  'no-typeof-undefined': S7741,
  'no-unnecessary-polyfills': S7742,
  'no-unreadable-iife': S7743,
  'no-useless-fallback-in-spread': S7744,
  'no-useless-length-check': S7745,
  'no-useless-promise-resolve-reject': S7746,
  'no-useless-spread': S7747,
  'no-zero-fractions': S7748,
  'numeric-separators-style': S7749,
  'prefer-array-find': S7750,
  'prefer-array-flat': S7751,
  'prefer-array-flat-map': S7752,
  'prefer-array-index-of': S7753,
  'prefer-array-some': S7754,
  'prefer-at': S7755,
  'prefer-blob-reading-methods': S7756,
  'prefer-class-fields': S7757,
  'prefer-code-point': S7758,
  'prefer-date-now': S7759,
  'prefer-default-parameters': S7760,
  'dom-node-dataset': S7761,
  'prefer-dom-node-remove': S7762,
  'prefer-export-from': S7763,
  'prefer-global-this': S7764,
  'prefer-includes': S7765,
  'prefer-math-min-max': S7766,
  'prefer-math-trunc': S7767,
  'prefer-modern-dom-apis': S7768,
  'prefer-modern-math-apis': S7769,
  'prefer-native-coercion-functions': S7770,
  'prefer-negative-index': S7771,
  'prefer-node-protocol': S7772,
  'prefer-number-properties': S7773,
  'prefer-prototype-methods': S7774,
  'prefer-regexp-test': S7775,
  'prefer-set-has': S7776,
  'prefer-set-size': S7777,
  'prefer-single-call': S7778,
  'prefer-string-raw': S7780,
  'prefer-string-replace-all': S7781,
  'prefer-string-trim-start-end': S7783,
  'prefer-structured-clone': S7784,
  'prefer-top-level-await': S7785,
  'prefer-type-error': S7786,
  'require-module-specifiers': S7787,
  'dynamically-constructed-templates': S7790,
  'no-session-cookies-on-static-assets': S8441,
  'dompurify-unsafe-config': S8479,
  'no-duplicate-test-title': S8754,
  'async-test-assertions': S8780,
  'no-empty-test-title': S8781,
  'hooks-before-test-cases': S8782,
  'no-forced-browser-interaction': S8783,
  'assertions-in-test-cases': S8784,
  'synchronous-suite-callback': S8785,
  'super-linear-regex': S8786,
  'prefer-native-lodash-alternative': S8907,
  'no-default-utility-imports': S8927,
  'memoize-cache-key': S8932,
  'no-required-prop-with-default': S8950,
  'no-mutating-props': S8951,
  'require-prop-types': S8957,
  'no-debug-commands-in-ui-tests': S8959,
  'no-mixed-completion-style': S8960,
  'require-explicit-emits': S8961,
  'require-typed-ref': S8962,
  'no-interpolation-in-inline-snapshots': S8967,
  'explicit-test-skip': S8968,
  'no-unnecessary-act': S8980,
  'no-global-regexp-flag-in-query': S8981,
  'require-v-for-key': S8982,
  'valid-v-for': S8984,
  'no-wait-for-side-effects': S8985,
  'no-use-v-if-with-v-for': S8987,
  'no-side-effects-in-computed-properties': S8988,
  'no-promise-in-fire-event': S8990,
  'no-empty-parameterized-test-dataset': S8998,
  'button-has-type': S9011,
  'no-wait-for-snapshot': S9012,
  'no-ref-as-operand': S9019,
  'prefer-find-by': S9020,
  'no-async-in-computed-properties': S9025,
  'await-async-queries': S9026,
  'testing-library-query-assertion': S9027,
  'synchronous-exception-assertions': S9072,
  'composite-assertions': S9073,
  'no-duplicate-parameterized-test-case': S9078,
  'require-prop-type-constructor': S9107,
  'no-debounce-throttle-in-render': S9114,
  'no-dupe-keys-S9128': S9128,
};
