/*
 * SonarQube JavaScript Plugin
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */


// Code generated by "npm run generate-meta". DO NOT EDIT.

package main

var ruleMetadataBySonarKey = map[string]ruleMetadata{
	"S100": {
		DefaultOptionsJSON: "[{\"format\":\"^[_a-z][a-zA-Z0-9]*$\"}]",
	},
	"S101": {
		DefaultOptionsJSON: "[{\"format\":\"^\\\\$?[A-Z][a-zA-Z0-9]*$\"}]",
	},
	"S103": {
		DefaultOptionsJSON: "[{\"code\":80,\"tabWidth\":4}]",
	},
	"S104": {
		DefaultOptionsJSON: "[{\"maximum\":1000}]",
	},
	"S106": {
		DefaultOptionsJSON: "[{}]",
	},
	"S107": {
		DefaultOptionsJSON: "[{\"max\":7}]",
	},
	"S108": {
		DefaultOptionsJSON: "[{\"allowEmptyCatch\":false}]",
	},
	"S109": {
		DefaultOptionsJSON: "[{\"ignore\":[0,1,-1,24,60],\"ignoreDefaultValues\":true,\"ignoreClassFieldInitialValues\":true,\"ignoreEnums\":true,\"ignoreNumericLiteralTypes\":true,\"ignoreReadonlyClassProperties\":true}]",
	},
	"S113": {
		DefaultOptionsJSON: "[\"always\"]",
	},
	"S117": {
		DefaultOptionsJSON: "[{\"format\":\"^[_$A-Za-z][$A-Za-z0-9]*$|^[_$A-Z][_$A-Z0-9]+$\"}]",
	},
	"S121": {
		DefaultOptionsJSON: "[\"all\"]",
	},
	"S122": {
		DefaultOptionsJSON: "[{\"max\":1}]",
	},
	"S124": {
		DefaultOptionsJSON: "[{\"regularExpression\":\"\",\"message\":\"The regular expression matches this comment.\",\"flags\":\"\"}]",
	},
	"S131": {
		DefaultOptionsJSON: "[{\"considerDefaultExhaustiveForUnions\":true,\"requireDefaultForNonUnion\":true}]",
	},
	"S134": {
		DefaultOptionsJSON: "[{\"maximumNestingLevel\":3}]",
	},
	"S138": {
		DefaultOptionsJSON: "[{\"maximum\":200}]",
	},
	"S139": {
		DefaultOptionsJSON: "[{\"ignorePattern\":\"^\\\\s*[^\\\\s]+$\"}]",
	},
	"S878": {
		DefaultOptionsJSON: "[{\"allowInParentheses\":true}]",
	},
	"S905": {
		DefaultOptionsJSON: "[{\"allowShortCircuit\":true,\"allowTaggedTemplates\":true,\"allowTernary\":true,\"enforceForJSX\":true}]",
	},
	"S1067": {
		DefaultOptionsJSON: "[{\"max\":3}]",
	},
	"S1068": {
		RequiredEcmaVersion: 2022,
	},
	"S1105": {
		DefaultOptionsJSON: "[\"1tbs\",{\"allowSingleLine\":true}]",
	},
	"S1117": {
		DefaultOptionsJSON: "[{\"hoist\":\"all\"}]",
	},
	"S1128": {
		RequiredEcmaVersion: 2015,
	},
	"S1131": {
		DefaultOptionsJSON: "[{\"skipBlankLines\":false,\"ignoreComments\":false}]",
	},
	"S1186": {
		DefaultOptionsJSON: "[{\"allow\":[\"arrowFunctions\",\"constructors\",\"private-constructors\"]}]",
	},
	"S1192": {
		DefaultOptionsJSON: "[{\"threshold\":3,\"ignoreStrings\":\"application/json\"}]",
	},
	"S1438": {
		DefaultOptionsJSON: "[\"always\"]",
	},
	"S1440": {
		DefaultOptionsJSON: "[\"smart\"]",
	},
	"S1441": {
		DefaultOptionsJSON: "[\"double\",{\"allowTemplateLiterals\":\"never\",\"avoidEscape\":false,\"ignoreStringLiterals\":false}]",
	},
	"S1451": {
		DefaultOptionsJSON: "[{\"headerFormat\":\"\",\"isRegularExpression\":false}]",
	},
	"S1479": {
		DefaultOptionsJSON: "[30]",
	},
	"S1537": {
		DefaultOptionsJSON: "[\"never\"]",
	},
	"S1539": {
		DefaultOptionsJSON: "[\"safe\"]",
	},
	"S1541": {
		DefaultOptionsJSON: "[{\"threshold\":10}]",
	},
	"S1656": {
		DefaultOptionsJSON: "[{\"props\":true}]",
	},
	"S1751": {
		DefaultOptionsJSON: "[{\"ignore\":[]}]",
	},
	"S1788": {
		RequiredEcmaVersion: 2015,
	},
	"S2004": {
		DefaultOptionsJSON: "[{\"threshold\":4}]",
	},
	"S2068": {
		DefaultOptionsJSON: "[{\"passwordWords\":[\"password\",\"pwd\",\"passwd\",\"passphrase\"]}]",
	},
	"S2094": {
		DefaultOptionsJSON: "[{\"allowConstructorOnly\":false,\"allowEmpty\":false,\"allowStaticOnly\":true,\"allowWithDecorator\":true}]",
	},
	"S2208": {
		RequiredEcmaVersion: 2015,
	},
	"S2376": {
		DefaultOptionsJSON: "[{\"enforceForTSTypes\":false,\"enforceForClassMembers\":true,\"getWithoutSet\":false,\"setWithoutGet\":true}]",
	},
	"S2427": {
		DefaultOptionsJSON: "[\"always\"]",
	},
	"S2430": {
		DefaultOptionsJSON: "[{\"capIsNew\":false,\"capIsNewExceptions\":[\"Array\",\"Boolean\",\"Date\",\"Error\",\"Function\",\"Number\",\"Object\",\"RegExp\",\"String\",\"Symbol\",\"BigInt\"],\"newIsCap\":true,\"newIsCapExceptions\":[],\"properties\":false}]",
	},
	"S2688": {
		DefaultOptionsJSON: "[{\"enforceForIndexOf\":false,\"enforceForSwitchCase\":true}]",
	},
	"S2814": {
		DefaultOptionsJSON: "[{\"builtinGlobals\":false,\"ignoreDeclarationMerge\":true}]",
	},
	"S2999": {
		DefaultOptionsJSON: "[{\"considerJSDoc\":false}]",
	},
	"S3317": {
		RequiredEcmaVersion: 2015,
	},
	"S3353": {
		DefaultOptionsJSON: "[{\"destructuring\":\"all\",\"ignoreReadBeforeAssign\":true}]",
		RequiredEcmaVersion: 2015,
	},
	"S3498": {
		RequiredEcmaVersion: 2015,
	},
	"S3499": {
		RequiredEcmaVersion: 2015,
	},
	"S3500": {
		RequiredEcmaVersion: 2015,
	},
	"S3504": {
		RequiredEcmaVersion: 2015,
	},
	"S3512": {
		RequiredEcmaVersion: 2015,
	},
	"S3513": {
		RequiredEcmaVersion: 2015,
	},
	"S3514": {
		RequiredEcmaVersion: 2015,
	},
	"S3524": {
		DefaultOptionsJSON: "[{\"requireParameterParentheses\":false,\"requireBodyBraces\":false}]",
		RequiredEcmaVersion: 2015,
	},
	"S3525": {
		RequiredEcmaVersion: 2015,
	},
	"S3531": {
		RequiredEcmaVersion: 2015,
	},
	"S3533": {
		RequiredEcmaVersion: 2015,
	},
	"S3723": {
		DefaultOptionsJSON: "[\"always-multiline\"]",
	},
	"S3776": {
		DefaultOptionsJSON: "[15]",
	},
	"S3786": {
		RequiredEcmaVersion: 2015,
	},
	"S3799": {
		DefaultOptionsJSON: "[{\"allowObjectPatternsAsParameters\":true}]",
	},
	"S3812": {
		DefaultOptionsJSON: "[{\"enforceForOrderingRelations\":false}]",
	},
	"S3834": {
		RequiredEcmaVersion: 2015,
	},
	"S3863": {
		RequiredEcmaVersion: 2015,
	},
	"S4023": {
		DefaultOptionsJSON: "[{\"allowSingleExtends\":true}]",
	},
	"S4123": {
		RequiredEcmaVersion: 2017,
	},
	"S4125": {
		DefaultOptionsJSON: "[{\"requireStringLiterals\":false}]",
	},
	"S4137": {
		DefaultOptionsJSON: "[{\"assertionStyle\":\"as\",\"objectLiteralTypeAssertions\":\"allow\"}]",
	},
	"S4144": {
		DefaultOptionsJSON: "[3]",
	},
	"S4275": {
		DefaultOptionsJSON: "[{\"allowImplicit\":false}]",
	},
	"S4326": {
		RequiredEcmaVersion: 2017,
	},
	"S4327": {
		DefaultOptionsJSON: "[{\"allowDestructuring\":true}]",
	},
	"S4328": {
		DefaultOptionsJSON: "[{\"whitelist\":[]}]",
	},
	"S4423": {
		RequiredDependencies: []string{"aws-cdk-lib"},
	},
	"S4622": {
		DefaultOptionsJSON: "[{\"threshold\":3}]",
	},
	"S4624": {
		RequiredEcmaVersion: 2015,
	},
	"S4634": {
		RequiredEcmaVersion: 2015,
	},
	"S4822": {
		RequiredEcmaVersion: 2017,
	},
	"S5604": {
		DefaultOptionsJSON: "[{\"permissions\":[\"geolocation\"]}]",
	},
	"S5693": {
		DefaultOptionsJSON: "[{\"fileUploadSizeLimit\":8000000,\"standardSizeLimit\":2000000}]",
	},
	"S5843": {
		DefaultOptionsJSON: "[{\"threshold\":20}]",
	},
	"S6245": {
		RequiredDependencies: []string{"aws-cdk-lib"},
	},
	"S6249": {
		RequiredDependencies: []string{"aws-cdk-lib"},
	},
	"S6252": {
		RequiredDependencies: []string{"aws-cdk-lib"},
	},
	"S6265": {
		RequiredDependencies: []string{"aws-cdk-lib"},
	},
	"S6270": {
		RequiredDependencies: []string{"aws-cdk-lib"},
	},
	"S6275": {
		RequiredDependencies: []string{"aws-cdk-lib"},
	},
	"S6281": {
		RequiredDependencies: []string{"aws-cdk-lib"},
	},
	"S6302": {
		RequiredDependencies: []string{"aws-cdk-lib"},
	},
	"S6303": {
		RequiredDependencies: []string{"aws-cdk-lib"},
	},
	"S6304": {
		RequiredDependencies: []string{"aws-cdk-lib"},
	},
	"S6308": {
		RequiredDependencies: []string{"aws-cdk-lib"},
	},
	"S6317": {
		RequiredDependencies: []string{"aws-cdk-lib"},
	},
	"S6319": {
		RequiredDependencies: []string{"aws-cdk-lib"},
	},
	"S6321": {
		RequiredDependencies: []string{"aws-cdk-lib"},
	},
	"S6325": {
		DefaultOptionsJSON: "[{\"disallowRedundantWrapping\":false}]",
	},
	"S6327": {
		RequiredDependencies: []string{"aws-cdk-lib"},
	},
	"S6329": {
		RequiredDependencies: []string{"aws-cdk-lib"},
	},
	"S6330": {
		RequiredDependencies: []string{"aws-cdk-lib"},
	},
	"S6332": {
		RequiredDependencies: []string{"aws-cdk-lib"},
	},
	"S6333": {
		RequiredDependencies: []string{"aws-cdk-lib"},
	},
	"S6418": {
		DefaultOptionsJSON: "[{\"secretWords\":\"api[_.-]?key,auth,credential,secret,token\",\"randomnessSensibility\":5}]",
	},
	"S6435": {
		RequiredDependencies: []string{"react"},
	},
	"S6439": {
		RequiredDependencies: []string{"react", "react-native"},
	},
	"S6440": {
		RequiredDependencies: []string{"react"},
	},
	"S6441": {
		RequiredDependencies: []string{"react"},
	},
	"S6442": {
		RequiredDependencies: []string{"react"},
	},
	"S6443": {
		RequiredDependencies: []string{"react"},
	},
	"S6478": {
		DefaultOptionsJSON: "[{\"allowAsProps\":false}]",
		RequiredDependencies: []string{"react"},
	},
	"S6480": {
		DefaultOptionsJSON: "[{\"ignoreRefs\":true,\"ignoreDOMComponents\":true}]",
	},
	"S6481": {
		RequiredDependencies: []string{"react"},
	},
	"S6509": {
		DefaultOptionsJSON: "[{}]",
	},
	"S6522": {
		RequiredEcmaVersion: 2015,
	},
	"S6523": {
		DefaultOptionsJSON: "[{\"disallowArithmeticOperators\":false}]",
		RequiredEcmaVersion: 2020,
	},
	"S6535": {
		DefaultOptionsJSON: "[{\"allowRegexCharacters\":[]}]",
	},
	"S6544": {
		DefaultOptionsJSON: "[{\"checksVoidReturn\":{\"attributes\":false,\"arguments\":false,\"properties\":false},\"ignoreIIFE\":true}]",
		RequiredEcmaVersion: 2017,
	},
	"S6550": {
		DefaultOptionsJSON: "[{\"allowBitwiseExpressions\":false}]",
	},
	"S6557": {
		RequiredEcmaVersion: 2015,
	},
	"S6606": {
		DefaultOptionsJSON: "[{\"allowRuleToRunWithoutStrictNullChecksIKnowWhatIAmDoing\":true,\"ignoreConditionalTests\":true,\"ignoreMixedLogicalExpressions\":true,\"ignoreTernaryTests\":false,\"ignorePrimitives\":true}]",
		RequiredEcmaVersion: 2020,
	},
	"S6643": {
		DefaultOptionsJSON: "[{\"exceptions\":[]}]",
	},
	"S6644": {
		DefaultOptionsJSON: "[{\"defaultAssignment\":true}]",
	},
	"S6647": {
		RequiredEcmaVersion: 2015,
	},
	"S6650": {
		DefaultOptionsJSON: "[{\"ignoreDestructuring\":false,\"ignoreImport\":false,\"ignoreExport\":false}]",
	},
	"S6653": {
		RequiredEcmaVersion: 2022,
	},
	"S6661": {
		RequiredEcmaVersion: 2018,
	},
	"S6671": {
		DefaultOptionsJSON: "[{\"allowThrowingAny\":true,\"allowThrowingUnknown\":true}]",
	},
	"S6746": {
		RequiredDependencies: []string{"react"},
	},
	"S6747": {
		DefaultOptionsJSON: "[{\"ignore\":[]}]",
		RequiredDependencies: []string{"react"},
	},
	"S6748": {
		RequiredDependencies: []string{"react"},
	},
	"S6749": {
		DefaultOptionsJSON: "[{\"allowExpressions\":true}]",
	},
	"S6750": {
		RequiredDependencies: []string{"react"},
	},
	"S6754": {
		DefaultOptionsJSON: "[{\"allowDestructuredState\":true}]",
		RequiredDependencies: []string{"react"},
	},
	"S6756": {
		RequiredDependencies: []string{"react"},
	},
	"S6757": {
		RequiredDependencies: []string{"react"},
	},
	"S6761": {
		RequiredDependencies: []string{"react"},
	},
	"S6763": {
		RequiredDependencies: []string{"react"},
	},
	"S6766": {
		DefaultOptionsJSON: "[{\"forbid\":[\">\",\"}\"]}]",
	},
	"S6767": {
		RequiredDependencies: []string{"react"},
	},
	"S6774": {
		RequiredDependencies: []string{"react"},
	},
	"S6775": {
		RequiredDependencies: []string{"react"},
	},
	"S6788": {
		RequiredDependencies: []string{"react"},
	},
	"S6789": {
		RequiredDependencies: []string{"react"},
	},
	"S6790": {
		RequiredDependencies: []string{"react"},
	},
	"S6791": {
		DefaultOptionsJSON: "[{\"checkAliases\":true}]",
		RequiredDependencies: []string{"react"},
	},
	"S6821": {
		DefaultOptionsJSON: "[{\"allowedInvalidRoles\":[\"text\"],\"ignoreNonDOM\":true}]",
	},
	"S6842": {
		DefaultOptionsJSON: "[{\"ul\":[\"listbox\"],\"li\":[\"option\"]}]",
	},
	"S6845": {
		DefaultOptionsJSON: "[{\"roles\":[\"tabpanel\"]}]",
	},
	"S6847": {
		DefaultOptionsJSON: "[{\"handlers\":[\"onClick\",\"onMouseDown\",\"onMouseUp\",\"onKeyPress\",\"onKeyDown\",\"onKeyUp\"]}]",
	},
	"S6957": {
		RequiredDependencies: []string{"react"},
	},
	"S7059": {
		RequiredEcmaVersion: 2017,
	},
	"S7641": {
		RequiredDependencies: []string{"@angular/core"},
	},
	"S7647": {
		RequiredDependencies: []string{"@angular/core"},
	},
	"S7648": {
		RequiredDependencies: []string{"@angular/core"},
	},
	"S7649": {
		RequiredDependencies: []string{"@angular/core"},
	},
	"S7650": {
		RequiredDependencies: []string{"@angular/core"},
	},
	"S7651": {
		RequiredDependencies: []string{"@angular/core"},
	},
	"S7652": {
		RequiredDependencies: []string{"@angular/core"},
	},
	"S7653": {
		RequiredDependencies: []string{"@angular/core"},
	},
	"S7654": {
		RequiredDependencies: []string{"@angular/core"},
	},
	"S7655": {
		RequiredDependencies: []string{"@angular/core"},
	},
	"S7656": {
		RequiredDependencies: []string{"@angular/core"},
	},
	"S7718": {
		DefaultOptionsJSON: "[{\"name\":\"error\",\"ignore\":[]}]",
	},
	"S7720": {
		RequiredEcmaVersion: 2015,
	},
	"S7721": {
		DefaultOptionsJSON: "[{\"checkArrowFunctions\":true}]",
	},
	"S7726": {
		RequiredEcmaVersion: 2015,
	},
	"S7728": {
		RequiredEcmaVersion: 2015,
	},
	"S7730": {
		RequiredEcmaVersion: 2017,
	},
	"S7732": {
		DefaultOptionsJSON: "[{\"useErrorIsError\":false,\"strategy\":\"loose\",\"include\":[],\"exclude\":[]}]",
	},
	"S7734": {
		RequiredEcmaVersion: 2015,
	},
	"S7741": {
		DefaultOptionsJSON: "[{\"checkGlobalVariables\":false}]",
	},
	"S7749": {
		DefaultOptionsJSON: "[{\"onlyIfContainsSeparator\":false,\"binary\":{\"minimumDigits\":0,\"groupLength\":4},\"octal\":{\"minimumDigits\":0,\"groupLength\":4},\"hexadecimal\":{\"minimumDigits\":0,\"groupLength\":2},\"number\":{\"minimumDigits\":5,\"groupLength\":3}}]",
	},
	"S7750": {
		DefaultOptionsJSON: "[{\"checkFromLast\":true}]",
		RequiredEcmaVersion: 2015,
	},
	"S7751": {
		DefaultOptionsJSON: "[{\"functions\":[]}]",
		RequiredEcmaVersion: 2019,
	},
	"S7752": {
		RequiredEcmaVersion: 2019,
	},
	"S7755": {
		DefaultOptionsJSON: "[{\"getLastElementFunctions\":[],\"checkAllIndexAccess\":false}]",
		RequiredEcmaVersion: 2022,
	},
	"S7757": {
		RequiredEcmaVersion: 2022,
	},
	"S7758": {
		RequiredEcmaVersion: 2015,
	},
	"S7760": {
		RequiredEcmaVersion: 2015,
	},
	"S7763": {
		DefaultOptionsJSON: "[{\"ignoreUsedVariables\":false}]",
		RequiredEcmaVersion: 2015,
	},
	"S7764": {
		RequiredEcmaVersion: 2020,
	},
	"S7765": {
		RequiredEcmaVersion: 2016,
	},
	"S7767": {
		RequiredEcmaVersion: 2015,
	},
	"S7769": {
		RequiredEcmaVersion: 2015,
	},
	"S7771": {
		RequiredEcmaVersion: 2022,
	},
	"S7773": {
		DefaultOptionsJSON: "[{\"checkInfinity\":false,\"checkNaN\":true}]",
		RequiredEcmaVersion: 2015,
	},
	"S7776": {
		RequiredEcmaVersion: 2015,
	},
	"S7777": {
		RequiredEcmaVersion: 2015,
	},
	"S7778": {
		DefaultOptionsJSON: "[{\"ignore\":[]}]",
	},
	"S7780": {
		RequiredEcmaVersion: 2015,
	},
	"S7781": {
		RequiredEcmaVersion: 2021,
	},
	"S7783": {
		RequiredEcmaVersion: 2019,
	},
	"S7784": {
		DefaultOptionsJSON: "[{\"functions\":[]}]",
		RequiredEcmaVersion: 2022,
	},
	"S7785": {
		RequiredModuleType: "module",
		RequiredEcmaVersion: 2022,
	},
}
