// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package prefer_string_starts_ends_with

import "github.com/go-json-experiment/json"
import "fmt"
import "reflect"

type PreferStringStartsEndsWithOptions struct {
	// Whether to allow equality checks against the first or last element of a string.
	AllowSingleElementEquality *PreferStringStartsEndsWithOptionsAllowSingleElementEquality `json:"allowSingleElementEquality,omitempty"`
}

type PreferStringStartsEndsWithOptionsAllowSingleElementEquality string

const PreferStringStartsEndsWithOptionsAllowSingleElementEqualityAlways PreferStringStartsEndsWithOptionsAllowSingleElementEquality = "always"
const PreferStringStartsEndsWithOptionsAllowSingleElementEqualityNever PreferStringStartsEndsWithOptionsAllowSingleElementEquality = "never"

var enumValues_PreferStringStartsEndsWithOptionsAllowSingleElementEquality = []interface{}{
	"always",
	"never",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PreferStringStartsEndsWithOptionsAllowSingleElementEquality) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_PreferStringStartsEndsWithOptionsAllowSingleElementEquality {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_PreferStringStartsEndsWithOptionsAllowSingleElementEquality, v)
	}
	*j = PreferStringStartsEndsWithOptionsAllowSingleElementEquality(v)
	return nil
}
