/*
 * SonarQube JavaScript Plugin
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */

// DO NOT EDIT! This file is autogenerated by "npm run generate-meta"

package org.sonar.css;

import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.annotation.Nullable;
import org.sonar.api.batch.rule.CheckFactory;
import org.sonar.api.batch.rule.Checks;
import org.sonar.api.rule.RuleKey;
import org.sonar.api.scanner.ScannerSide;
import org.sonar.css.rules.CssRule;
import org.sonar.css.rules.S1116;
import org.sonar.css.rules.S1128;
import org.sonar.css.rules.S125;
import org.sonar.css.rules.S1874;
import org.sonar.css.rules.S2260;
import org.sonar.css.rules.S4647;
import org.sonar.css.rules.S4648;
import org.sonar.css.rules.S4649;
import org.sonar.css.rules.S4650;
import org.sonar.css.rules.S4651;
import org.sonar.css.rules.S4652;
import org.sonar.css.rules.S4653;
import org.sonar.css.rules.S4654;
import org.sonar.css.rules.S4655;
import org.sonar.css.rules.S4656;
import org.sonar.css.rules.S4657;
import org.sonar.css.rules.S4658;
import org.sonar.css.rules.S4659;
import org.sonar.css.rules.S4660;
import org.sonar.css.rules.S4661;
import org.sonar.css.rules.S4662;
import org.sonar.css.rules.S4663;
import org.sonar.css.rules.S4664;
import org.sonar.css.rules.S4666;
import org.sonar.css.rules.S4667;
import org.sonar.css.rules.S4668;
import org.sonar.css.rules.S4670;
import org.sonar.css.rules.S5362;
import org.sonar.css.rules.S7923;
import org.sonar.css.rules.S7924;
import org.sonar.css.rules.S7925;
import org.sonar.plugins.javascript.bridge.StylelintRule;
import org.sonarsource.api.sonarlint.SonarLintSide;

@ScannerSide
@SonarLintSide
public class CssRules {

  public static final String CSS_PARSING_ERROR_STYLELINT_KEY = "CssSyntaxError";

  private final Map<String, RuleKey> stylelintKeyToRuleKey;
  private final Collection<CssRule> rules;

  public CssRules(CheckFactory checkFactory) {
    Checks<CssRule> checks = checkFactory
      .<CssRule>create(CssRulesDefinition.REPOSITORY_KEY)
      .addAnnotatedChecks(getRuleClasses());
    this.rules = checks.all();
    stylelintKeyToRuleKey = new HashMap<>();
    for (CssRule rule : rules) {
      RuleKey ruleKey = checks.ruleKey(rule);
      for (StylelintRule sr : rule.stylelintRules()) {
        stylelintKeyToRuleKey.put(sr.getKey(), ruleKey);
      }
    }
  }

  public static List<Class<?>> getRuleClasses() {
    return Collections.unmodifiableList(
      Arrays.asList(
        S125.class,
        S1116.class,
        S1128.class,
        S1874.class,
        S2260.class,
        S4647.class,
        S4648.class,
        S4649.class,
        S4650.class,
        S4651.class,
        S4652.class,
        S4653.class,
        S4654.class,
        S4655.class,
        S4656.class,
        S4657.class,
        S4658.class,
        S4659.class,
        S4660.class,
        S4661.class,
        S4662.class,
        S4663.class,
        S4664.class,
        S4666.class,
        S4667.class,
        S4668.class,
        S4670.class,
        S5362.class,
        S7923.class,
        S7924.class,
        S7925.class
      )
    );
  }

  @Nullable
  public RuleKey getActiveSonarKey(String stylelintKey) {
    return stylelintKeyToRuleKey.get(stylelintKey);
  }

  public List<StylelintRule> getStylelintRules() {
    return this.rules.stream()
      .flatMap(rule -> rule.stylelintRules().stream())
      .filter(sr -> !CSS_PARSING_ERROR_STYLELINT_KEY.equals(sr.getKey()))
      .toList();
  }
}
