/*
 * SonarQube JavaScript Plugin
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */
package org.sonar.plugins.javascript.api;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;
import org.sonar.plugins.javascript.api.estree.ESTree;

class JavaScriptAstServiceTest {

  private final JavaScriptAstService service = new JavaScriptAstService();

  @Test
  void should_return_program_for_valid_bytes() throws IOException {
    var result = service.getProgram(getSerializedProtoData());

    assertThat(result).isPresent();
    assertThat(result.get()).isInstanceOf(ESTree.Program.class);
    assertThat(result.get().body()).isNotEmpty();
  }

  @Test
  void should_return_empty_for_invalid_bytes() throws IOException {
    var result = service.getProgram(new byte[] { 42 });

    assertThat(result).isEmpty();
  }

  @Test
  void should_return_empty_for_empty_bytes() throws IOException {
    var result = service.getProgram(new byte[0]);

    assertThat(result).isEmpty();
  }

  private static byte[] getSerializedProtoData() throws IOException {
    // the clear version of serialized.proto is `packages/analysis/tests/jsts/parsers/fixtures/ast/base.js`
    // it was generated by writing to a file the serialized data in the test `packages/analysis/tests/jsts/parsers/ast.test.ts`
    return Files.readAllBytes(resolveTestFile("serialized.proto"));
  }

  private static Path resolveTestFile(String fileName) {
    var path = Path.of("src", "test", "resources", "files", fileName);
    if (path.toFile().exists()) {
      return path;
    }
    return Path.of("sonar-plugin", "bridge", "src", "test", "resources", "files", fileName);
  }
}
