"""Summarize generated DiffSIT JSON reports.

This script reads the manifest produced by prepare_diffsit_inputs.py and only
loads the JSON reports already generated by the workflow's shell DiffSIT loop.
"""

import argparse
import json
import sys
from pathlib import Path
from typing import Any

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from sit_pr_fps.common import resolve_path_under

COUNT_KEYS = (
    "projects",
    "base_count",
    "target_count",
    "new",
    "removed",
    "changed",
    "message_changes",
    "secondary_changes",
    "unchanged",
)


def path_under_cwd(label: str):
    def parse_path(value: str) -> Path:
        try:
            return resolve_path_under(Path.cwd(), value, label)
        except ValueError as err:
            raise argparse.ArgumentTypeError(str(err)) from err

    return parse_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Summarize DiffSIT JSON reports")
    parser.add_argument("--manifest", required=True, type=path_under_cwd("--manifest"))
    parser.add_argument("--summary-output", required=True, type=path_under_cwd("--summary-output"))
    return parser.parse_args()


def load_json_file(path: Path, label: str) -> Any:
    if not path.is_file():
        raise FileNotFoundError(f"{label} does not exist: {path}")
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as err:
        raise ValueError(f"{label} must be valid JSON: {path}: {err}") from err


def extract_summary(report: dict[str, Any], report_path: Path) -> dict[str, Any]:
    raw_summary = report.get("overall_summary")
    if raw_summary is None:
        raw_summary = report.get("summary")
    if not isinstance(raw_summary, dict):
        raise ValueError(f"DiffSIT report is missing summary data: {report_path}")

    summary = {key: int(raw_summary.get(key, 0) or 0) for key in COUNT_KEYS}
    if "overall_summary" not in report:
        summary["projects"] = 1

    only_in_base = raw_summary.get("only_in_base", [])
    only_in_target = raw_summary.get("only_in_target", [])
    if not isinstance(only_in_base, list) or not isinstance(only_in_target, list):
        raise ValueError(f"DiffSIT report has invalid project-only lists: {report_path}")
    summary["only_in_base"] = only_in_base
    summary["only_in_target"] = only_in_target
    return summary


def aggregate_results(results: list[dict[str, Any]]) -> dict[str, Any]:
    overall = {key: sum(result[key] for result in results) for key in COUNT_KEYS}
    overall["only_in_base"] = [
        {"language": result["language"], "project": project} for result in results for project in result["only_in_base"]
    ]
    overall["only_in_target"] = [
        {"language": result["language"], "project": project}
        for result in results
        for project in result["only_in_target"]
    ]
    return overall


def summarize_reports(manifest_path: Path, summary_output: Path) -> dict[str, Any]:
    manifest = load_json_file(manifest_path, "manifest")
    runs = manifest.get("runs")
    if not isinstance(runs, list):
        raise ValueError(f"manifest must contain a runs array: {manifest_path}")

    results = []
    for run in runs:
        if not isinstance(run, dict):
            raise ValueError(f"manifest run entries must be objects: {manifest_path}")

        reports = run.get("reports")
        if not isinstance(reports, dict) or not isinstance(reports.get("json"), str):
            raise ValueError(f"manifest run is missing reports.json: {manifest_path}")

        report_path = resolve_path_under(Path.cwd(), reports["json"], "reports.json")
        report = load_json_file(report_path, "DiffSIT JSON report")
        if not isinstance(report, dict):
            raise ValueError(f"DiffSIT JSON report must be an object: {report_path}")

        summary = extract_summary(report, report_path)
        results.append(
            {
                "language": run.get("language"),
                "rule_keys": run.get("rule_keys", []),
                "rule_filter": run.get("rule_filter", ""),
                "report_path": str(report_path),
                **summary,
            }
        )

    payload = {
        "total": len(results),
        "overall": aggregate_results(results),
        "results": results,
    }

    summary_output.parent.mkdir(parents=True, exist_ok=True)
    summary_output.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    return payload


def main() -> int:
    args = parse_args()
    try:
        payload = summarize_reports(args.manifest, args.summary_output)
    except (FileNotFoundError, ValueError) as err:
        print(f"Error: {err}", file=sys.stderr)
        return 1

    print(f"Wrote DiffSIT summary to {args.summary_output} ({payload['total']} run(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
