/*
 * SonarQube JavaScript Plugin
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */
import { debug, info } from '../../../../shared/src/helpers/logging.js';
import type { NormalizedAbsolutePath } from '../../../../shared/src/helpers/files.js';

const READ_CHARACTERS_LIMIT = 2048;
const COMMENT = String.raw`/\*.*\*/`;
const OPERATOR = '[!;+(]';
const OPTIONAL_FUNCTION_NAME = '(?: [_$a-zA-Z][_$a-zA-Z0-9]*)?';
const COMMENT_OPERATOR_FUNCTION = new RegExp(
  COMMENT + String.raw`\s*` + OPERATOR + 'function ?' + OPTIONAL_FUNCTION_NAME + String.raw`\(`,
  's',
);
const GENERATED_HEADER_PATTERNS = [
  /@generated\b/i,
  /@auto-generated\b/i,
  /\bautomatically generated\b/i,
  /\bautogenerated\b/i,
  /\bgenerated code\b/i,
  /\bdo not edit\b/i,
  /\bgenerated by\b/i,
];
let hasInfoBeenLogged = false;

export function filterBundle(filePath: NormalizedAbsolutePath, input: string) {
  if (hasGeneratedHeaderComment(input)) {
    debug(
      `File ${filePath} was excluded because it contains an explicit generated code marker in its header comment. (Disable detection with sonar.javascript.detectBundles=false)`,
    );
    logGeneratedCodeInfoOnce();
    return false;
  }

  if (!filterBundleCode(input)) {
    debug(
      `File ${filePath} was excluded because it looks like a bundle. (Disable detection with sonar.javascript.detectBundles=false)`,
    );
    logGeneratedCodeInfoOnce();
    return false;
  }
  return true;
}

export function filterBundleCode(input: string) {
  const firstCharacters = input.substring(0, READ_CHARACTERS_LIMIT);
  return !COMMENT_OPERATOR_FUNCTION.test(firstCharacters);
}

export function hasGeneratedHeaderComment(input: string) {
  const leadingCommentHeader = extractLeadingCommentHeader(input);
  return (
    leadingCommentHeader.length > 0 &&
    GENERATED_HEADER_PATTERNS.some(pattern => pattern.test(leadingCommentHeader))
  );
}

function extractLeadingCommentHeader(input: string) {
  const firstCharacters = input.substring(0, READ_CHARACTERS_LIMIT);
  let index = 0;
  let header = '';

  if (firstCharacters.charCodeAt(0) === 0xfeff) {
    index++;
  }

  while (index < firstCharacters.length) {
    index = skipWhitespace(firstCharacters, index);

    if (firstCharacters.startsWith('#!', index)) {
      const shebangEnd = firstCharacters.indexOf('\n', index);
      index = shebangEnd === -1 ? firstCharacters.length : shebangEnd + 1;
      continue;
    }

    if (firstCharacters.startsWith('//', index)) {
      const lineEnd = firstCharacters.indexOf('\n', index);
      const nextIndex = lineEnd === -1 ? firstCharacters.length : lineEnd + 1;
      header += firstCharacters.slice(index, nextIndex);
      index = nextIndex;
      continue;
    }

    if (firstCharacters.startsWith('/*', index)) {
      const commentEnd = firstCharacters.indexOf('*/', index + 2);
      const nextIndex = commentEnd === -1 ? firstCharacters.length : commentEnd + 2;
      header += firstCharacters.slice(index, nextIndex);
      index = nextIndex;
      continue;
    }

    break;
  }

  return header;
}

function skipWhitespace(input: string, index: number) {
  while (index < input.length && /\s/.test(input[index])) {
    index++;
  }
  return index;
}

function logGeneratedCodeInfoOnce() {
  if (!hasInfoBeenLogged) {
    info(
      'Some of the project files were automatically excluded because they looked like generated code. Enable debug logging to see which files were excluded. You can disable bundle detection by setting sonar.javascript.detectBundles=false',
    );
    hasInfoBeenLogged = true;
  }
}
