/*
 * SonarQube JavaScript Plugin
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */
import { debug, info } from '../../../../shared/src/helpers/logging.js';
import type { NormalizedAbsolutePath } from '../../../../shared/src/helpers/files.js';

const READ_CHARACTERS_LIMIT = 2048;
const COMMENT = String.raw`/\*.*\*/`;
const OPERATOR = '[!;+(]';
const OPTIONAL_FUNCTION_NAME = '(?: [_$a-zA-Z][_$a-zA-Z0-9]*)?';
const COMMENT_OPERATOR_FUNCTION = new RegExp(
  COMMENT + String.raw`\s*` + OPERATOR + 'function ?' + OPTIONAL_FUNCTION_NAME + String.raw`\(`,
  's',
);
const BYTE_ORDER_MARK = 0xfeff;
const GENERATED_HEADER_PATTERNS = [
  /@generated\b/i,
  /@auto-generated\b/i,
  /\bautomatically generated\b/i,
  /\bautogenerated\b/i,
  /\bgenerated code\b/i,
  /\bdo not edit\b/i,
];
let hasInfoBeenLogged = false;

export function filterBundle(filePath: NormalizedAbsolutePath, input: string) {
  if (hasGeneratedHeaderComment(input)) {
    debug(
      `File ${filePath} was excluded because it contains an explicit generated code marker in its header comment. (Disable detection with sonar.javascript.detectBundles=false)`,
    );
    logGeneratedCodeInfoOnce();
    return false;
  }

  if (!filterBundleCode(input)) {
    debug(
      `File ${filePath} was excluded because it looks like a bundle. (Disable detection with sonar.javascript.detectBundles=false)`,
    );
    logGeneratedCodeInfoOnce();
    return false;
  }
  return true;
}

export function filterBundleCode(input: string) {
  const firstCharacters = input.substring(0, READ_CHARACTERS_LIMIT);
  return !COMMENT_OPERATOR_FUNCTION.test(firstCharacters);
}

export function hasGeneratedHeaderComment(input: string) {
  const leadingCommentHeader = extractLeadingCommentHeader(input);
  return (
    leadingCommentHeader.length > 0 &&
    (GENERATED_HEADER_PATTERNS.some(pattern => pattern.test(leadingCommentHeader)) ||
      hasGeneratedByCommentLine(leadingCommentHeader))
  );
}

function extractLeadingCommentHeader(input: string) {
  const firstCharacters = input.substring(0, READ_CHARACTERS_LIMIT);
  let index = startsWithBom(firstCharacters) ? 1 : 0;
  let header = '';

  while (index < firstCharacters.length) {
    index = skipWhitespace(firstCharacters, index);

    const shebangEnd = findShebangEnd(firstCharacters, index);
    if (shebangEnd !== undefined) {
      index = shebangEnd;
      continue;
    }

    const lineCommentEnd = findLineCommentEnd(firstCharacters, index);
    if (lineCommentEnd !== undefined) {
      header += firstCharacters.slice(index, lineCommentEnd);
      index = lineCommentEnd;
      continue;
    }

    const blockCommentEnd = findBlockCommentEnd(firstCharacters, index);
    if (blockCommentEnd !== undefined) {
      header += firstCharacters.slice(index, blockCommentEnd);
      index = blockCommentEnd;
      continue;
    }

    break;
  }

  return header;
}

function startsWithBom(input: string) {
  return input.codePointAt(0) === BYTE_ORDER_MARK;
}

function findShebangEnd(input: string, index: number) {
  if (!input.startsWith('#!', index)) {
    return undefined;
  }
  return nextLineIndex(input, index);
}

function findLineCommentEnd(input: string, index: number) {
  if (!input.startsWith('//', index)) {
    return undefined;
  }
  return nextLineIndex(input, index);
}

function findBlockCommentEnd(input: string, index: number) {
  if (!input.startsWith('/*', index)) {
    return undefined;
  }

  const commentEnd = input.indexOf('*/', index + 2);
  return commentEnd === -1 ? input.length : commentEnd + 2;
}

function nextLineIndex(input: string, index: number) {
  const lineEnd = input.indexOf('\n', index);
  return lineEnd === -1 ? input.length : lineEnd + 1;
}

function hasGeneratedByCommentLine(input: string) {
  return input.split('\n').some(line => stripCommentPrefix(line).startsWith('Generated by'));
}

function stripCommentPrefix(line: string) {
  let index = skipWhitespace(line, 0);
  index = skipCommentPrefix(line, index);
  index = skipWhitespace(line, index);
  return line.slice(index);
}

function skipWhitespace(input: string, index: number) {
  while (index < input.length && /\s/.test(input[index])) {
    index++;
  }
  return index;
}

function skipCommentPrefix(line: string, index: number) {
  if (line.startsWith('//', index)) {
    return skipRepeatedCharacter(line, index + 2, '/');
  }

  if (line.startsWith('/*', index)) {
    return skipRepeatedCharacter(line, index + 2, '*');
  }

  return skipRepeatedCharacter(line, index, '*');
}

function skipRepeatedCharacter(input: string, index: number, character: string) {
  while (index < input.length && input[index] === character) {
    index++;
  }
  return index;
}

function logGeneratedCodeInfoOnce() {
  if (!hasInfoBeenLogged) {
    info(
      'Some of the project files were automatically excluded because they looked like generated code. Enable debug logging to see which files were excluded. You can disable bundle detection by setting sonar.javascript.detectBundles=false',
    );
    hasInfoBeenLogged = true;
  }
}
