/*
 * SonarQube JavaScript Plugin
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import merge from 'lodash.merge';
import { header, listRulesDir, RULES_FOLDER } from './helpers.js';
import * as generatedMetas from '../packages/analysis/src/jsts/rules/metas.js';
import * as ruleModules from '../packages/analysis/src/jsts/rules/rules.js';

type GeneratedRuleMetaModule = {
  sonarKey: string;
  meta?: {
    defaultOptions?: unknown[];
  };
  requiredDependency?: string[];
  requiredModuleType?: 'module' | 'commonjs';
  requiredEcmaVersion?: number;
};

type RuleModule = {
  meta?: {
    defaultOptions?: unknown[];
  };
};

type BridgeRuleMetadata = {
  sonarKey: string;
  defaultOptions: unknown[];
  requiredDependency: string[];
  requiredModuleType?: 'module' | 'commonjs';
  requiredEcmaVersion?: number;
};

const DIRNAME = dirname(fileURLToPath(import.meta.url));
const REPOSITORY_ROOT = join(DIRNAME, '..');
const OUTPUT_PATH = join(
  REPOSITORY_ROOT,
  'sonar-plugin',
  'bridge',
  'src',
  'main',
  'go',
  'sonar-server',
  'generated_rule_metadata.go',
);

const bridgeDefaultOptionsOverrides: Record<string, unknown[]> = {
  // The Go bridge maps S131 to a single underlying rule, so it needs the
  // non-union "missing default" behavior encoded in the options.
  S131: [{ requireDefaultForNonUnion: true }],
};

export async function generateGoRuleMetadata() {
  const metadata = await collectBridgeRuleMetadata();
  const contents = `${header}

// Code generated by "npm run generate-meta". DO NOT EDIT.

package main

var ruleMetadataBySonarKey = map[string]ruleMetadata{
${metadata.map(formatRuleMetadata).join('\n')}
}
`;

  await mkdir(dirname(OUTPUT_PATH), { recursive: true });
  await writeFile(OUTPUT_PATH, contents);
}

async function collectBridgeRuleMetadata(): Promise<BridgeRuleMetadata[]> {
  const metadata: BridgeRuleMetadata[] = [];
  const generatedMetaBySonarKey = generatedMetas as Record<string, GeneratedRuleMetaModule>;
  const ruleModuleBySonarKey = ruleModules as Record<string, RuleModule>;

  for (const sonarKey of await listRulesDir()) {
    const module = generatedMetaBySonarKey[sonarKey];
    const ruleModule = ruleModuleBySonarKey[sonarKey];
    if (!module) {
      throw new Error(`Missing generated meta module for ${sonarKey}`);
    }
    if (!ruleModule) {
      throw new Error(`Missing rule module for ${sonarKey}`);
    }

    const requiredDependency = module.requiredDependency ?? [];
    const requiredModuleType = module.requiredModuleType;
    const requiredEcmaVersion = module.requiredEcmaVersion;
    const baseDefaultOptions = ruleModule.meta?.defaultOptions ?? module.meta?.defaultOptions ?? [];
    const defaultOptions = merge(
      [],
      baseDefaultOptions,
      bridgeDefaultOptionsOverrides[module.sonarKey ?? sonarKey] ?? [],
    );

    if (
      defaultOptions.length === 0 &&
      requiredDependency.length === 0 &&
      requiredModuleType === undefined &&
      requiredEcmaVersion === undefined
    ) {
      continue;
    }

    metadata.push({
      sonarKey: module.sonarKey ?? sonarKey,
      defaultOptions,
      requiredDependency,
      requiredModuleType,
      requiredEcmaVersion,
    });
  }

  return metadata;
}

function formatRuleMetadata(ruleMeta: BridgeRuleMetadata) {
  const fields: string[] = [];

  if (ruleMeta.defaultOptions.length > 0) {
    fields.push(`DefaultOptionsJSON: ${JSON.stringify(JSON.stringify(ruleMeta.defaultOptions))},`);
  }
  if (ruleMeta.requiredDependency.length > 0) {
    fields.push(`RequiredDependencies: ${formatStringSlice(ruleMeta.requiredDependency)},`);
  }
  if (ruleMeta.requiredModuleType !== undefined) {
    fields.push(`RequiredModuleType: ${JSON.stringify(ruleMeta.requiredModuleType)},`);
  }
  if (ruleMeta.requiredEcmaVersion !== undefined) {
    fields.push(`RequiredEcmaVersion: ${ruleMeta.requiredEcmaVersion},`);
  }

  return `\t${JSON.stringify(ruleMeta.sonarKey)}: {\n${fields
    .map(field => `\t\t${field}`)
    .join('\n')}\n\t},`;
}

function formatStringSlice(values: string[]) {
  return `[]string{${values.map(value => JSON.stringify(value)).join(', ')}}`;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await generateGoRuleMetadata();
}
