/*
 * SonarQube JavaScript Plugin
 * Copyright (C) SonarSource SÃ rl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource SÃ rl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import globalsPkg from 'globals';
import { header } from './helpers.js';

const DIRNAME = dirname(fileURLToPath(import.meta.url));
const REPOSITORY_ROOT = join(DIRNAME, '..');
const OUTPUT_PATH = join(
  REPOSITORY_ROOT,
  'server-go',
  'sonar-server',
  'generated_environment_globals.go',
);

type EnvironmentGlobals = Record<string, boolean>;

export async function generateGoEnvironmentGlobals() {
  const envEntries = Object.entries(globalsPkg)
    .filter(([, globals]) => globals && typeof globals === 'object')
    .map(([environment, globals]) => [environment, globals as EnvironmentGlobals] as const)
    .sort(([left], [right]) => left.localeCompare(right));

  const contents = `${header}

// Code generated by "npm run generate-meta". DO NOT EDIT.

package main

var environmentGlobalsByName = map[string]map[string]bool{
${envEntries.map(formatEnvironmentGlobals).join('\n')}
}
`;

  await mkdir(dirname(OUTPUT_PATH), { recursive: true });
  await writeFile(OUTPUT_PATH, contents);
}

function formatEnvironmentGlobals([environment, globals]: readonly [string, EnvironmentGlobals]) {
  const globalEntries = Object.entries(globals).sort(([left], [right]) =>
    left.localeCompare(right),
  );
  const lines = globalEntries.map(
    ([name, value]) => `\t\t${JSON.stringify(name)}: ${value ? 'true' : 'false'},`,
  );

  return `\t${JSON.stringify(environment)}: {\n${lines.join('\n')}\n\t},`;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await generateGoEnvironmentGlobals();
}
