/*
 * SonarQube JavaScript Plugin
 * Copyright (C) 2011-2025 SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the Sonar Source-Available License Version 1, as published by SonarSource SA.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */
// https://sonarsource.github.io/rspec/#/rspec/S2999/javascript

// DO NOT EDIT! This file is autogenerated by "npm run generate-meta"

import type { SonarMeta } from '../helpers/generate-meta.js';
export * from './meta.js';

export const meta = {
  type: 'problem',
  docs: {
    description: '"new" should only be used with functions and classes',
    recommended: true,
    url: 'https://sonarsource.github.io/rspec/#/rspec/S2999/javascript',
    requiresTypeChecking: true,
  },
  fixable: undefined,
  deprecated: false,
  defaultOptions: [
    {
      considerJSDoc: false,
    },
  ],
} satisfies SonarMeta['meta'];

export const sonarKey = 'S2999';
export const scope = 'Main';
export const languages: ('js' | 'ts')[] = ['js', 'ts'];
export const requiredDependency = [];
