/*
 * SonarQube JavaScript Plugin
 * Copyright (C) 2011-2025 SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the Sonar Source-Available License Version 1, as published by SonarSource SA.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */
// https://sonarsource.github.io/rspec/#/rspec/S6321/javascript

// DO NOT EDIT! This file is autogenerated by "npm run generate-meta"

import type { SonarMeta } from '../helpers/generate-meta.js';
export * from './meta.js';

export const meta = {
  type: 'problem',
  docs: {
    description: 'Administration services access should be restricted to specific IP addresses',
    recommended: true,
    url: 'https://sonarsource.github.io/rspec/#/rspec/S6321/javascript',
    requiresTypeChecking: false,
  },
  fixable: undefined,
  deprecated: false,
  defaultOptions: [],
} satisfies SonarMeta['meta'];

export const sonarKey = 'S6321';
export const scope = 'Main';
export const languages: ('js' | 'ts')[] = ['js', 'ts'];
export const requiredDependency = ['aws-cdk-lib'];
