name: Cleanup PR Resources

on:
  pull_request:
    types:
      - closed

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  cleanup:
    name: Cleanup PR caches and artifacts
    runs-on: warp-custom-ubuntu-24-04
    permissions:
      actions: write
    steps:
      - uses: SonarSource/ci-github-actions/pr_cleanup@v1
