name: Releasability Status
on:
  workflow_run:
    workflows: [ "Build" ]  # Name must match the name of the build workflow
    types: [ completed ]
    branches:
      - master
      - dogfood-*
      - branch-*

jobs:
  releasability-status:
    name: Releasability status
    runs-on: sonar-xs # Use any runner
    permissions:
      id-token: write
      statuses: write
      contents: read
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      -   uses: SonarSource/gh-action_releasability/releasability-status@v3
          with:
            optional_checks: "Jira"
          env:
            GITHUB_TOKEN: ${{ github.token }}
